### ISSUE TITLE
New line, Version support

### ISSUE THREAD

**Issue by IRAQIG4MER** [Puharesource/TitleManager#100]
First of all.. Thank you for your amazing work, I never seen a better titles plugins than yours ♥
I just have couple questions.. i hope you can answer them :)
1. does v2.0.6 support v1.8.8 (MC)? and is it working well on it?
2. When i use ( \n ) the new line variable in header and/or footer it won't work.. in old versions (v1.5.11) it was supported but now i have no idea, I'm trying to use it in header and footer but it won't work at all, I tried using ( %newline% ) and it didn't work too. So i just wanted to know if it supported or not.. and if it not can you support it because i really need it :)
Thank you again
Picture: http://i.imgur.com/bDhQdVl.png

Ayham Alali (IRAQIG4MER).

**Comment by Puharesource** [comment]
New lines are now added by creating a list like so:
```
header:
- 'Line #1'
- 'Line #2'
```

**Comment by craze** [comment]
Prior to v2 I used \n in animations, but also this is no longer working. An example on how to use multiple lines in animations now as well would be very appreciated. :-)

**Comment by Puharesource** [comment]
@craze That's not possible anymore, but is work in progress (I've got a a lot of work lately, but once I get the time, I'll fix it)

See #104 for more information in the meantime. :)
