### ISSUE TITLE
Variables Not Working 

### ISSUE THREAD

**Issue by Starmanfan** [Puharesource/TitleManager#101]
Hey!

So here is my problem, since I updated to the last version of Tittle Manager (2.0.6) I can,t use variables anymore. It just comes up as "Welcome, {player}" . I can.t use variables on the tab menu either.. hope this gets fixed soon.

**Comment by Puharesource** [comment]
You're need to write %{player}

**Comment by mauricecaaaaaben** [comment]
maybe you should read the changelog lmfao

**Comment by Starmanfan** [comment]
Sorry ;/
