### ISSUE TITLE
Broken variable

### ISSUE THREAD

**Issue by Twonox** [Puharesource/TitleManager#102]
The variable `{SAFE-ONLINE}` is broke.

**Comment by Puharesource** [comment]
You need to write `${SAFE-ONLINE}`

**Comment by Twonox** [comment]
Ok thanks :)

**Comment by Twonox** [comment]
It does't work :/

**Comment by Twonox** [comment]
I need write it with `%`, not with `$`

**Comment by Puharesource** [comment]
Oh yeah, sorry `%{SAFE-ONLINE}`
