### ISSUE TITLE
Scripts don't maintain message display if in subtitle

### ISSUE THREAD

**Issue by TrevorSayre** [Puharesource/TitleManager#105]
Input:
/tm bc Restarting server\nin ${count_down:10}

Expected result:
Title is shown as "Restarting server" with subtitle "in 10" where the subtitle counts down from 10

Actual result:
The title and subtitle display correctly, but for only 5 ticks then disappear

**Comment by Puharesource** [comment]
That's very strange behavior, it even fades out as if it had been a single message all along.

Until I find a fix, just use the `-stay` parameter an example would be `/tm bc -stay=200 Restarting server\nin ${count_down:10}`
