### ISSUE TITLE
Scripts and placeholders with parameters causes failed output if multiple are present

### ISSUE THREAD

**Issue by TrevorSayre** [Puharesource/TitleManager#107]
Working code:
```
  header:
    - ''
    - '&3Elements Community'
    - ''
    - '${left-to-right}'
    - ''
    - '&6Score: &aDeaths'
    - '&bsince Jan 22nd, 2017'
    - ''
```

Working image:
<img width="339" alt="working" src="https://cloud.githubusercontent.com/assets/421548/22229524/4441f078-e1a6-11e6-8320-b3ca0844921c.png">

Failing code:
```
  header:
    - ''
    - '${shine:Elements Community}'
    - ''
    - '${left-to-right}'
    - ''
    - '&6Score: &aDeaths'
    - '&bsince Jan 22nd, 2017'
    - ''
```

Failing image:
<img width="339" alt="working_not" src="https://cloud.githubusercontent.com/assets/421548/22229532/49ec7ee4-e1a6-11e6-9a32-87301326e160.png">

**Comment by Puharesource** [comment]
Does this only happen whenever you use the shine script, or does this also happen when you use other scripts?

**Comment by TrevorSayre** [comment]
It's happening with marquee, text_delete, and text_write as well. I also tested using a string with no spaces (e.g. `${shine:ElementsCommunity}`) and the bug still occurs.

**Comment by Puharesource** [comment]
Hmmm... I'll see what I can do

**Comment by Puharesource** [comment]
A user that uses placeholders with parameters also has this issue: 
http://image.prntscr.com/image/c314c6eb0aff42eea51e31948131f61a.png
https://cdn.discordapp.com/attachments/251558187155718145/274280887548510208/unknown.png
