### ISSUE TITLE
ActionBar fadeIn,stay,fadeout

### ISSUE THREAD

**Issue by Rocologo** [Puharesource/TitleManager#108]
Hi, I'm the dev of MobHunting and I'm using TitleManager API V2 in my plugin.

One of my users want the actionbar messages to stay longer, and I have tried to figure out howto, but all the developers examples is without fadein,stay,fadeout? 

Is it possible to use fadein,stay,fadeout for actionbars?

Kind regards
Rocologo

**Comment by Puharesource** [comment]
Unfortunately it is not, you'll have to repeat the same message for the duration you want the message to be shown. This is a client side limitation.
