### ISSUE TITLE
Server RAM & TPS in real time

### ISSUE THREAD

**Issue by LemonLight** [Puharesource/TitleManager#109]
Could you add the follow placeholders please ? 

RAM and TPS, it will be nice ! :)

**Comment by LemonLight** [comment]
And player coordinates, i forgot..

**Comment by Puharesource** [comment]
The TPS placeholder is in the works, see #106 for that.

Also, PlaceholderAPI might have the other placeholders, so check that out, also 😃

**Comment by LemonLight** [comment]
Oh yes I forgot P.API
Thanks :P

**Comment by LemonLight** [comment]
Hi,

I am re-opening because I can't make the work the $tps function :(

Here there is my line : 
```
footer: 
- ' &cSanté&8: &a${tps:[fade-in;stay;fade-out]FULL|SHORT|1|5|15}&8/&a20 &cRAM&8: &a%server_ram_used%&8/&a%server_ram_total%'
```

**Comment by Puharesource** [comment]
${TPS} hasn't been added yet
Take a look at: #106

**Comment by LemonLight** [comment]
Ok thanks I will try :) Will you add it in the future ?

**Comment by Puharesource** [comment]
Yes :)
