### ISSUE TITLE
Ideas!

### ISSUE THREAD

**Issue by ItsMennyo** [Puharesource/TitleManager#110]
I have a few ideas for this plugin :D

- A custom permission for a specific announcements.
- Positive numbers on the side of the scoreboard (instead of negative numbers)
- Custom tab tags.
- TPS placeholder

**Comment by Puharesource** [comment]
Positive numbers are available as of 4745c096c6f71a1166528db2ec405b089cee1e7b

**Comment by Puharesource** [comment]
TPS placeholder is available as of 5d1a3dbe8dd964314370052f3022957ee1539729
