### ISSUE TITLE
Tablist Server name 

### ISSUE THREAD

**Issue by Roy416** [Puharesource/TitleManager#111]
when holding tab, the server name kind of spazzes into different letters when the shine starts.

**Comment by ItsMennyo** [comment]
What is your config. place a link via pastebin.com

**Comment by Puharesource** [comment]
@ItsMennyo No need to use pastebin, just surround your config with the following ``` or use gist

**Comment by Roy416** [comment]
I see what I was doing wrong. I think I might have put &b before the actual server name and not in the brackets. Also I tried putting the ping above the amount of online players and I get 2 question marks. 

I put this as one of the footers: - '&bâ—? &3&lPing:'

**Comment by Wundero** [comment]
Running localhost shouldn't affect the functions of a plugin whatsoever. You should also post your config which causes the two "?" to appear so that we can help to fix the issue. As @Puharesource said, you can use gist or ``` to post it.

**Comment by Puharesource** [comment]
The issue with the question marks are most likely caused by unicode characters on Windows.

Take a look at this guide: https://github.com/Puharesource/TitleManager/wiki/Unicode---UTF-8-characters-for-TitleManager
