### ISSUE TITLE
Announcer enabled even when using-config is false

### ISSUE THREAD

**Issue by Spirit55555** [Puharesource/TitleManager#119]
The announcer part of the config is enabled, even when `using-config` is set to `false`.

I believe a check is missing around here:
https://github.com/Puharesource/TitleManager/blob/5d1a3dbe8dd964314370052f3022957ee1539729/src/main/kotlin/io/puharesource/mc/titlemanager/TitleManagerPlugin.kt#L268

**Comment by Puharesource** [comment]
Yeah, it'll be an easy fix, for now just disable the feature manually until I've made the changes
