### ISSUE TITLE
TabMenu isn't removed

### ISSUE THREAD

**Issue by matthewggg** [Puharesource/TitleManager#12]
I assume that tabmenu is the writings on top and bottom of the tab.
When you join a server using TitleManager, and a tabmenu is set, it will be transfered and you will keep it on the next server you join, if that server has not set a tabmenu (i.e. not using the plugin).

I'm sorry I can't check the version of the plugin for you, as I am not the one running it, I have just noticed the bug happening with a server I play on. Both servers are using Spigot 1.8 R0.1 Snapshot

**Comment by Wundero** [comment]
This is a glitch with Minecraft itself, as it keeps the data from server to server. I have seen what you mean, but there is no way to fix this unless the spigot team does.

**Comment by Puharesource** [comment]
Just like @Wundero said, this is a client bug that I can't fix. I think this was fixed with the 1.8.1 client, if you're still on 1.8; try updating to 1.8.1
