### ISSUE TITLE
Scoreboard & mcMMO

### ISSUE THREAD

**Issue by TheosisPvP** [Puharesource/TitleManager#120]
Hello,

I posted this issue in the "Discussion" section of this plugin a couple of months ago and it was replied to by the owner saying that they would keep it in mind, also directing me to this page in order to post any other issues.

The issue is that when the mcMMO scoreboard is enabled by a player (by typing /mcstats etc.), it doesn't show up, as the scoreboard from TitleManager is overriding (not sure if that's the correct term) it. I was wondering if it was possible to make it so that the scoreboard would disappear if an mcMMO scoreboard is active and re-appear when the mcMMO scoreboard disappears.

Regards,
TheosisPvP/Short

**Comment by DaDMaR** [comment]
sorry just found this after posting similar request - lol so love the idea

**Comment by chillerkraft** [comment]
good luck

**Comment by OhCreative** [comment]
+1 Would love a high priority on this.

**Comment by DaDMaR** [comment]
fixed use " /tm scoreboard toggle  "
to turn on/off TM scoreboard allowing you to see the mcMMO scoreboard
or as I also do -  in mcMMO config yml  -  put "=true" to print to chat - will then print to chat and mcmmo scoreboard
