### ISSUE TITLE
API Remove Scoreboard Non-Functional

### ISSUE THREAD

**Issue by ReeceyBoi81** [Puharesource/TitleManager#121]
I've recently used the API you provide to remove the scoreboard from the player - however this only removes the functionality of the scoreboard (effects) and does not wipe their scoreboard clean.

Is this intended?

**Comment by Puharesource** [comment]
No, this is not intended.

**Comment by ReeceyBoi81** [comment]
Do you have an ETA on when there may be a possible fix?

**Comment by Puharesource** [comment]
No, as I'm quite busy atm, will fix it asap though
