### ISSUE TITLE
Animations dont work in the header on tablist

### ISSUE THREAD

**Issue by OGTrumpetDaddy** [Puharesource/TitleManager#134]
the animations work on the footer of the tablist. Though for some reason the same animations wont work on the header
![2017-05-14_16 04 55](https://cloud.githubusercontent.com/assets/28692232/26037720/261e1250-38bf-11e7-922d-aaebabca5c52.png)

**Comment by Puharesource** [comment]
This is fixed with the upcoming version of TitleManager, please join the Discord group to download the pre-release.
