### ISSUE TITLE
Request - toggle the scoreboard on/off - Request

### ISSUE THREAD

**Issue by DaDMaR** [Puharesource/TitleManager#137]
Request:...can we have a in game command to toggle the scoreboard on/off
I need this so I can see my mcMMO stats.

OR

Super cool version of this would be to use the mcMMO command "mcstats" to shutdown the TitleManager scoreboard for "X seconds" as the mcMMO stats are temporarily displayed ????

Love this plugin - I had used previous incarnation(MC1.8-->) - the new current version, is very good and much faster.
Thank you.

**Comment by Puharesource** [comment]
Duplicates of #125 and #120
