### ISSUE TITLE
1.12 TitleManager, Action Bar messages not working!

### ISSUE THREAD

**Issue by DarkmanBree** [Puharesource/TitleManager#138]
Actionbar messages from TitleManager not working in Full 1.12  #Release.

An internal error occured while attempting to perform this command. #

**Comment by Puharesource** [comment]
Could you send me the error you might be getting in console? And are you on version 2.0.7?

**Comment by DarkmanBree** [comment]
Yes, I am in version 2.0.7, but I don't know how, but it somehow got fixed by itself now??? It works again.

I'll contact again if I get any further problems, Thank you for your time!
