### ISSUE TITLE
TitleManager scoreboard in multiple server will cause bungee disconnection

### ISSUE THREAD

**Issue by xion87** [Puharesource/TitleManager#139]
I noticed from when i installed titlemanager and enabled scoreboard, players are randomly disconected from bungee server when trying to connect...ecc... no errors... I am using viaversion and waterfall. Disablind titlemanager and enabling featherboard it work without issues

**Comment by Puharesource** [comment]
What's the disconnect message players get? And what version of TitleManager are you on?

**Comment by xion87** [comment]
I am using TitleManager 2.0.7, No errors, it happen only when they try to switch from a server to another showing the red bungeecord error message "that server maybe is down blabla"

**Comment by xion87** [comment]
Yeah i confirm the issue happen if i use 2 titlemanager scoreboard in 2 different server

**Comment by Puharesource** [comment]
But it doesn't happen to everyone, I'm assuming?

**Comment by xion87** [comment]
it happen it randomly to all players

**Comment by Puharesource** [comment]
Alright thanks for letting me know, I'll take a look later today or tomorrow

**Comment by Puharesource** [comment]
Try the latest version (2.0.8). Under `bandwidth` please enable `prevent-duplicate-packets` and I suggest increasing the tick rate of the tab and scoreboard to 1000 if you can live with only having updates every second.

**Comment by iiLegit** [comment]
Hi, I have the same issue with being kicked for the scoreboard already existing... I put the tick on both to 1000 and that doesn't resolve anything.

**Comment by Puharesource** [comment]
@xion87 Have you tried testing this yet?
