### ISSUE TITLE
Animation fade doesn't work properly

### ISSUE THREAD

**Issue by ADTX4869** [Puharesource/TitleManager#140]
I try to create some animation then I realize the fade in and fade out isn't working properly, it just stay and disappear without fade.
[20;10;0]a
[20;40;60]b
[20;10;20]c
That is my sample, it instantly show then after few second it just disappear without fade.

**Comment by Puharesource** [comment]
Where are you testing this? Because the fade values only work for title messages

**Comment by ADTX4869** [comment]
I use /tm bc ${test}
