### ISSUE TITLE
Bungeecord count - RedisBungee support.

### ISSUE THREAD

**Issue by blijgozertje** [Puharesource/TitleManager#144]
Hey,

I am using redisbungee this means that I have multiple bungeecord servers. 

The playercount is only showing 1 server and not all of them.

Could you add redisbungee support?

**Comment by elderlabs** [comment]
I suggest doing this the way Holographic Displays does, which pings each server individually, instead of querying via bungee. My network also has multiple bungees and requires this feature.

Thank you.

**Comment by Puharesource** [comment]
This is already a feature of the `bungeecord-online` placeholder (which broken atm, see #112). For the time being simply use PlaceholderAPI's placeholders for that functionality.
