### ISSUE TITLE
1.7.10 user cannot join in the server

### ISSUE THREAD

**Issue by pZeno** [Puharesource/TitleManager#145]
I'm writing here cause you told to do. This is the error: 
internal exception io.netty.handler.codec.decoderexception java.io.ioexception bad packet id 71
This happens only with 1.7.10 users.
My server is 1.7.10/1.8 only
copy paste of /version:
This server is running CraftBukkit version
git-PaperSpigot-1.7.9-R0.2-273-g5811366 (MC: 1.7.10)
(Implementing API version 1.7.10-R0.1-SNAPSHOT)
If you guys can tell me how to fix I would really appreciate it 👍

**Comment by Puharesource** [comment]
The only way TitleManager is able to check whether or not a player is on 1.7 or 1.8 is if you're using the Spigot ProtocolHack, that used to be used to allow 1.8 users to join a 1.7 server.

**Comment by Puharesource** [comment]
Should be fixed by f2671a098fc4af57c0bb2a81df9d163fa2b3bd34
