### ISSUE TITLE
[Feature Request] Add an Option to show Ping in Tablist

### ISSUE THREAD

**Issue by CDAGaming** [Puharesource/TitleManager#148]
Title mostly says it all, would be a good feature to inclue in the tablist for players

**Comment by Puharesource** [comment]
I'm guessing you mean next to players names? TitleManager doesn't edit the contents of the player list, only the header and footer as this has the least amount of risk of running into conflicts with other plugins.

If not, then you can simply add the `%{ping}` placeholders to the header or footer.

**Comment by CDAGaming** [comment]
Yes, i meant the header and footer, thx for the answer
