### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by Puharesource** [Puharesource/TitleManager#15]
To keep people from complaining and, I'll be adding compatibility for all 1.8 version INCLUDING the protocol hack.

**Comment by Techcable** [comment]
Maybe you can use my [Title class](https://gist.github.com/Techcable/c6a5caad442a220b4dab).
It supports protocol hack, 1.8, and 1.8.3.

**Comment by Puharesource** [comment]
I'm pretty close to being done with this already :)

However, I just need to add the Protocol Hack version and it'll be done: https://github.com/Puharesource/TitleManager/tree/master/plugins/TitleManager/src/main/java/io/puharesource/mc/titlemanager/backend/reflections/managers

This will also allow for future hooks, if the NMS source decides to change again :P

**Comment by Puharesource** [comment]
37fb372 Added support for both 1.8.3 and 1.8

Now I just need to add Protocol Hack support :smile:

**Comment by Puharesource** [comment]
f188a2c bfc0207 Finished! :+1:
