### ISSUE TITLE
Add toggle for actionbar messages

### ISSUE THREAD

**Issue by Beags** [Puharesource/TitleManager#151]
Hey,

Can you add a toggle for the action bar messages?

**Comment by Nedjii** [comment]
Is it coming one day ?

**Comment by Nedjii** [comment]
up

**Comment by Puharesource** [comment]
@Nedjii 
I'm guessing the toggle would be so that you wouldn't get any automatic actionbar messages?

**Comment by Nedjii** [comment]
Yes, a command with permission that would allow to prevent recieving automatic actionbar messages.
