### ISSUE TITLE
TAB List Prefix Not Showing

### ISSUE THREAD

**Issue by JimBoZhong** [Puharesource/TitleManager#160]
![image](https://user-images.githubusercontent.com/33611432/32706122-c761b8da-c855-11e7-8d55-e086b72cf620.png)
![image](https://user-images.githubusercontent.com/33611432/32706216-8ac2e876-c856-11e7-8730-fe52722a7275.png)

I am using the latest Titlemangaer,HealthBar and ColoredTags
it shows prefix when i stop my movement and it disappear when i move
How do i set it always shown?

**Comment by Puharesource** [comment]
The player list names and prefixes aren't controlled by TitleManager
