### ISSUE TITLE
Using SuperVanish but players can see me in tab

### ISSUE THREAD

**Issue by iskandarluqman** [Puharesource/TitleManager#165]
Heres an image. (https://imgur.com/VM7SYaA) One of my players screenshot. If you cant tell, The players online in tab dan scoreboard, both said 3 which means yes Im in vanish but still show in tab. Can you fix it?

**Comment by Puharesource** [comment]
That's an issue with SuperVanish, however, there's most likely no issue at all as I'm pretty sure you will always be able to see yourself on the scoreboard.
