### ISSUE TITLE
BUG Mcmmo and TitleManager scoreboard

### ISSUE THREAD

**Issue by zBoringDrop** [Puharesource/TitleManager#176]
So, if Mcmmo spawns a scoreboard, title manager scoreboard has the priority on Mcmmo board.. so a player can't see the board.
There is a fix?

**Comment by untuned** [comment]
Disable the scoreboard.

**Comment by zBoringDrop** [comment]
Why? Other plugin have the compatibilities with mcmmo scoreboard.. why don't add this hook to titlemanager?
