### ISSUE TITLE
Placeholder %{safe-online} doesn't work with EssentialsX and VanishNoPacket!

### ISSUE THREAD

**Issue by ghost** [Puharesource/TitleManager#178]
Placeholder %{safe-online} doesn't work with:
EssentialsX
VanishNoPacket

**Comment by Lightcaster5** [comment]
I am having this same issue.

**Comment by Lightcaster5** [comment]
I have EssentialsX, VanishNoPacket, and SuperVanish installed

**Comment by fmohican** [comment]
Just use PAPI and `%essentials_safe_online%`

**Comment by Puharesource** [comment]
Should be fixed with the latest version (2.1.6)
