### ISSUE TITLE
The repos are down

### ISSUE THREAD

**Issue by Nicofisi** [Puharesource/TitleManager#179]
Both http://repo.puha.io/nexus/content/repositories/releases/ and https://repo.puha.io/repo/

**Comment by gcallant** [comment]
Can also confirm this- looks like the domains have expired (http://whois.domaintools.com/puha.io with NameCheap) and are just displaying parked info.

**Comment by Puharesource** [comment]
Yeah sorry, the auto renewal had screwed up

**Comment by Nicofisi** [comment]
Hmm, why close the issue when the repo is still down xD

**Comment by Puharesource** [comment]
@Nicofisi Uhhh... didn't realize that it wasn't, but it's up now ^^
