### ISSUE TITLE
Memory leak (OOM), server hangs

### ISSUE THREAD

**Issue by BestMark** [Puharesource/TitleManager#185]
Hello,
After 2 hours of work, TitleManager 2.1.1 uses all of the RAM on my server, as result, it causes OOM. I did the heap dump, and now I'm sure that the problem is in the plugin, as Eclipse Memory Analyzer says.
Software: Paper 1.12.2 (latest build), TitleManager 2.1.1
![memleak1](https://user-images.githubusercontent.com/18399104/43991210-91d587aa-9d70-11e8-9f29-b752415b2f64.PNG)
![default](https://user-images.githubusercontent.com/18399104/43991211-91f34042-9d70-11e8-99d0-98d176afb750.PNG)
Please, fix it as soon as possible.

**Comment by BestKvant** [comment]
Yep, that's true.

I enabled %server_ram_used% and %server_ram_total% placeholders.
In half a day my server was suffering lags and %server_ram_used% value was very close to %server_ram_total%.

I started suffering from this troubles, causing lags after updating to last version of TitleManager plugin.
I hope, you will fix it pretty fast.

**Comment by Puharesource** [comment]
I'll be fixing this now, I didn't have a computer at my disposal yesterday, so sorry for the delay
