### ISSUE TITLE
Can't setup two identical lines in the scoreboard

### ISSUE THREAD

**Issue by LemonLight** [Puharesource/TitleManager#190]
Hi!

I found a bug with the scoreboard : we can't setup two identical lines in the scoreboard.

TitleManager version : 2.1.3
Spigot version : 1.13.1-R0.1-SNAPSHOT (git-Spigot-38536ab-8164f4b)

Example : 
```
lines:
  - '&0&l&m                       '
  - '   &5» &d» &e&l%{bungeecord-online} &7&l/ &e&l300 &d« &5«'
  - '&0&l&m                       '
```
With the above configuration, the first line disappear
To fix the problem with have to do this :
```
lines:
  - '&0&l&m                       &r'
  - '   &5» &d» &e&l%{bungeecord-online} &7&l/ &e&l300 &d« &5«'
  - '&0&l&m                       '
```

**Comment by Puharesource** [comment]
This is an issue with Minecraft itself and is also mentioned in the config's comments.
