### ISSUE TITLE
1.13.2 tps freezes tablist

### ISSUE THREAD

**Issue by Possibly-Pos** [Puharesource/TitleManager#194]
Title sums it up when using the %{tps} placeholder in tabmenu it no longer updates. I'm unsure of the cause. My config for the tab menu.

  header:
  - '§6╔═════════════╗'

  footer:
  - '§6╠═════════════╣§r'
  - 'Time &d%{24h-world-time}&r'
  - 'Ping §d%player_ping%&r | TPS %{tps}&r'
  - '§6╚═════════════╝'

**Comment by mattboy9921** [comment]
I've also experienced this. TPS from PlaceholderAPI flat out isn't recognized. Using Paper.
