### ISSUE TITLE
TitleManager issue

### ISSUE THREAD

**Issue by GamerRO28** [Puharesource/TitleManager#196]
I have checked the console, no errors, everything is clean, when I join I get the tab, but when I rejoin I don't get it anymore, I have to reload the plugin everytime I join, I'm on 1.8.8 spigot.

EDIT: Now it seems like even reload won't do anything..

**Comment by Nyderas** [comment]
This happens to me on a 1.12.2 server as well!

**Comment by Puharesource** [comment]
Should be fixed with the latest release
