### ISSUE TITLE
PROBLEMS IN %{group} and {money}

### ISSUE THREAD

**Issue by leridgamer** [Puharesource/TitleManager#198]
![CAP 1](https://user-images.githubusercontent.com/48574432/54401421-4268ac80-468d-11e9-8519-4500f237b2bc.png)

**Comment by leridgamer** [comment]
Do not Jala Do not Know Why I Speak Spanish This I Tradusco So They Understand
---------------------------
RANK in Spanish It's RANG O
MONEY in Spanish Es Dine Ro

**Comment by leridgamer** [comment]
If You Could Solve It Or Tell Me How To Do It I Would Appreciate It

**Comment by Puharesource** [comment]
You need the plugin `Vault` for these placeholders to work and it's not `%{money}` but it is `%{balance}`
