### ISSUE TITLE
Tablist disabling itself upon player relog.

### ISSUE THREAD

**Issue by starwarsfreak219** [Puharesource/TitleManager#201]
I noticed an issue with the Tablist disabling itself when a player relogs(It only disables for that specific player). When I go to a different world, it will come back and work how it should. I noticed this issue after installed CMI. With Essentials it does not have this issue. The issue seems to be completely stemmed from a custom footer, with a custom header everything works fine, but with a custom footer, it disables the Tablist.

Server Version: 1.8.8
Minecraft Version: 1.8.9
Plugin Version: 2.1.3

Please look into this! Thanks in advance!

**Comment by Puharesource** [comment]
Should be fixed with the latest release
