### ISSUE TITLE
PlaceHolderHook fails every time

### ISSUE THREAD

**Issue by ReimannMC** [Puharesource/TitleManager#202]
Hi there,

Since my last restart my titlemanager scoreboard stopped showing 90% of what was there before.
Not just placeholders, but also alot of text. 

I get this error everytime:

`[ERROR] Could not pass event PlayerJoinEvent to TitleManager v2.1.3

java.lang.AbstractMethodError: me/clip/placeholderapi/PlaceholderHook.onPlaceholderRequest(Lorg/bukkit/entity/Player;Ljava/lang/String;)Ljava/lang/String;

http://prntscr.com/o0opb1 (Screenshot of entire error)

http://prntscr.com/o0opv6 (Screenshot of FATAL error upon /tm reload)

But I have no idea what it  means... Is my PlaceHolderAPI outdated?

EDIT 12-06-2019

Narrowed the problem down to Vault. I used these placeholders in the titlemanager config:

- %vault_eco_balance%
- %vault_rank%

Did Titlemanager suddenly drop support for these placeholders? 

Thanks,
Tantillus.

**Comment by Puharesource** [comment]
Not quite sure what's causing this, I have a feeling it's caused by whatever plugin is hooked into Vault that's providing the economy and rank features. Like Essentials, GroupManager/PermissionsEx etc...

**Comment by ReimannMC** [comment]
> Not quite sure what's causing this, I have a feeling it's caused by whatever plugin is hooked into Vault that's providing the economy and rank features. Like Essentials, GroupManager/PermissionsEx etc...

Hi there,

Is it expected that Titlemanager 2.1.4 fixes this issue?

**Comment by Puharesource** [comment]
No, as this is a recent issue that occurred without me ever changing anything on my end. I do think it's caused by an issue out of my control. I will keep a look at possible causes, but I have my doubts that I can do anything.

**Comment by ReimannMC** [comment]
Thanks for the support,

I'll keep my eye on future updates!
