### ISSUE TITLE
Bungeecord Support!

### ISSUE THREAD

**Issue by YepImRobbie** [Puharesource/TitleManager#21]
No bungeetab out there has animations, that's where this plugin can just slide in and be the best. :) I don't necessarily want the sections like bungeetab plugins out there provide, just everyone on one tab would be very nice! :)

**Comment by Puharesource** [comment]
Alright, I'll try to see if I can work something out :)

**Comment by Puharesource** [comment]
I just realised you wanted everyone on the tab (Which my plugin doesn't do) however! My plugin does now, allow for you to display the playercount of other servers on the tabmenu
