### ISSUE TITLE
Mineplex / Hypixel style shine animation

### ISSUE THREAD

**Issue by UntoldFury** [Puharesource/TitleManager#22]
Hello!
One thing I would love to see added on the server would be something like a flashing welcome message. Basically I want it to look similar to how Mineplex has their's set up, where it can scroll maybe the latest news in front of the players. Also, could you possibly make the fade in/ fade out/ stay in seconds if possible? It was really confusing until I realized it worked in ticks. Thanks! :)

**Comment by Wundero** [comment]
You could set up an animation that scrolls (repeat the sequence "&f " for spaces, then add colors) via the animation generator on Puharesource's website. You would have to change the news every time you wanted to update the news, unless you made a plugin to hook in and do it that way. If you really wanted to, though I wouldn't recommend it, you could fork the repository and add something like what you want yourself. I might look into a scrolling text animation variable but I don't have time right now. I hope this helped in some way.

**Comment by Puharesource** [comment]
Scrolling text has already been added as an issue #19 

But you did come up with a good idea and that was the shiny effect that Mineplex has, so that's what this issue is going to address.
