### ISSUE TITLE
PlaceholderAPI - Need Help with format

### ISSUE THREAD

**Issue by JamzyTV** [Puharesource/TitleManager#226]
So basically I have Title-manager setup, as well as PlaceholdersAPI, and I am using FactionsUUID, in which the format on PlaceholderAPI it is set as "%factionsuuid_faction_name%" to see the faction name, though the format on Title-manager is "%{name}", anyone know a way to transfer, this, I know its possible

**Comment by Puharesource** [comment]
You can use both
`%factionsuuid_faction_name%` for factions and `%{name}` for the player's name
