### ISSUE TITLE
Config should be false by default

### ISSUE THREAD

**Issue by danbovey** [Puharesource/TitleManager#23]
When you restart the server with TitleManager freshly installed, it shows players who join back a really unprofessional giant message which was along the lines of "sweg sweggy craft".

Sounds kind of counter-intuitive but I think you should think about either changing the default text for welcome messages and the tablist to false so that text (that the server owner didn't create) doesn't appear or make the default text a bit more generic like `&7TitleManager Placeholder`.

Gave you a good review because it's a brilliant plugin in every other aspect!

**Comment by Puharesource** [comment]
4aff24b Fixed
