### ISSUE TITLE
Scoreboard Incompatibility CombatLogX && MobArena

### ISSUE THREAD

**Issue by fmohican** [Puharesource/TitleManager#230]
Hello!
I'm using your last version of TitleManager (2.1.5), on the last paper (git-Paper-175) on 1.14.4.

The MobArena uses Scoreboard only when player are in area (when fight) and CombatLogX uses scoreboard only in PvP, the problem is TitleManager overwrite both of them.

Please look at: https://youtu.be/5rdtPJkKZV0
and: https://youtu.be/E3VDGZIhwI8

![image](https://user-images.githubusercontent.com/8583317/64039686-deb33c80-cb63-11e9-8148-c9f2b46792dd.png)

**Comment by fmohican** [comment]
Issues still persist in `TitleManager 2.1.6`
I just build myself from `Master`.

**Comment by Puharesource** [comment]
It's a known issue and is a problem with every other plugin that uses the scoreboard. I'll take a look at the issue but I don't know when there will be a fix as I've got a full time job and some freelance work on the side, that takes priority over this.

**Comment by fmohican** [comment]
Any news on this?

**Comment by SladeHazard** [comment]
+1

**Comment by Puharesource** [comment]
CombatLogX integration will be available in the upcoming version 2.2.0. MobArena doesn't give me an indication of when their Scoreboard is being shown though

**Comment by Puharesource** [comment]
Also the compatibility I've added only works for CombatLogX 10.0.0.0 or the Beta version that's on Blobman's Jenkins
