### ISSUE TITLE
TPS Not Updating

### ISSUE THREAD

**Issue by rudipratm** [Puharesource/TitleManager#234]
Okay so I have this plugin installed on my server. And I place a TPS's placeholder to see my TPS. These TPS show up after reloading this plugin, but it's not updating.

Here's the lines section:
 ```
- '&a&lWorld:'
- '&f%{world}'

- '&r&r&r'
- '&b&lCoins:'
- '&f%{money}'

- '&r&r&r&r'
- '&c&lOnline:'
- '&f%{online}'

- '&r&r&r&r&r'
- '&d&lTPS:'
- '%{tps}'
```

**Comment by Puharesource** [comment]
Please use the bug template you were asked to fill when creating an issue, I need more information.
