### ISSUE TITLE
Help please /tm wont work

### ISSUE THREAD

**Issue by Mahid102938** [Puharesource/TitleManager#24]
when i do /tm it replys saying /tm. Idk why i tried like all versions. Im using http://gyazo.com/d2e4da0d9b461c0a02fb47c5519a37f7 .

**Comment by MasterWhisker** [comment]
Updated to Spigot 1.8.3.

**Comment by Puharesource** [comment]
This is a user bug, either update to Spigot 1.8.3 or downgrade to 1.8.3
