### ISSUE TITLE
player-list header/footer breaks with prevent-duplicate-packets: false

### ISSUE THREAD

**Issue by bugreports69** [Puharesource/TitleManager#242]
**Describe the bug**
The player-list will flicker and only show the header OR footer at any given time when `prevent-duplicate-packets` is set to false on version `2.1.5`.

**To Reproduce**
Configure a header and a footer for the player-list (and enable them)
Set prevent-duplicate-packets to false
Join server and look at player-list (hold TAB by default)

**Expected behavior**
See both header and footer.

**Screenshots**
NA

**Stacktrace / Error**
NA

**Server information:**
 - TitleManager version: 2.1.5
 - Spigot version: Spigot or Paper 1.15

**Additional context**
Bug is NOT present with Titlemanager version 2.1.4 (and Paper 1.15)

**Comment by bugreports69** [comment]
Issue is NOT with 1.15, but with TitleManager verison 2.1.5 and the prevent-duplicate-packets setting. I've updated the bug report with new information.

**Comment by Puharesource** [comment]
Should be fixed with the latest version (2.1.6)
