### ISSUE TITLE
SCOREBOARD ERROR

### ISSUE THREAD

**Issue by SladeHazard** [Puharesource/TitleManager#247]
Plugin Version: 2.1.6
Server Version: 1.12.2 Paper
Scoreboard config: https://hastebin.com/ahajevegak.bash
Error screenshot: https://imgur.com/a/LsHf8K0
How to reproduce: Login onto a 1.12.2 paper server using 1.15.2 client the last line of the tab doesn't support formats like &m &n pls FIX server is using viarewind,viaversion,viabackwards

**Comment by SladeHazard** [comment]
bump

**Comment by SladeHazard** [comment]
BRUHHH

**Comment by SladeHazard** [comment]
bump u gonna fix or what?!@!!!

**Comment by SladeHazard** [comment]
...

**Comment by Puharesource** [comment]
You honestly don't deserve to get this bug fixed, but nonetheless I'll fix it for others experiencing the same issue.

**Comment by Puharesource** [comment]
Alright, so I've gathered some information about the bug. If there's hovering text being shown to the player, then the formatting will actually show. So this includes title messages, actionbar messages and item names when choosing a new item in your hotbar.

This is quite strange and could be a bug in Minecraft, though I'd have to ask others for help to know for sure.

**Comment by SladeHazard** [comment]
> You honestly don't deserve to get this bug fixed, but nonetheless I'll fix it for others experiencing the same issue.

Go away noob replying after 2 months im using featherboard now doesn't happen with it

**Comment by Puharesource** [comment]
The problem doesn't seem to be fixable as it's a bug with Minecraft.
