### ISSUE TITLE
Weird header behavior. 

### ISSUE THREAD

**Issue by Zcamt** [Puharesource/TitleManager#250]
Plain and simple, the header isn't showing in the tab list :/

**Expected behavior**
Well I would expect the header to show up, but only the footer shows up for me :/

**Screenshots**
http://prntscr.com/r1d5r0

**Stacktrace / Error**
There isn't anything showing in the console :/

**Server information:**
 - TitleManager version: 2.1.5]
 - Spigot version: PaperSpigot 1.8.8]

**Comment by Puharesource** [comment]
This should be fixed with the latest changes, keep an eye out for version 2.1.7
