### ISSUE TITLE
Title Manager Error

### ISSUE THREAD

**Issue by BOTAsiann** [Puharesource/TitleManager#251]
**Describe the bug**
So I run a bungeecord server that is 1.12.2 and everytime i do /tm reload i get the error
in the pastebin

**Stacktrace / Error**
https://pastebin.com/sJVGARxk

**Server information:**
 - TitleManager version: [Example:. 2.1.6]
 - Spigot version: [Spigot 1.12]

**Comment by Puharesource** [comment]
Should be fixed with the latest release
