### ISSUE TITLE
Scoreboard disappears

### ISSUE THREAD

**Issue by MaxIsV** [Puharesource/TitleManager#253]
**Describe the bug**
Scoreboard and Player List periodically disappear

**To Reproduce**
I changed the plugin settings a little and reloaded it.

**Stacktrace / Error**
no error

**Server information:**
 - TitleManager version: 2.1.6 
 - Spigot version: PaperSpigot 1.12

**Additional context**
No additional context

**Comment by MaxIsV** [comment]
I found out new information. Scoreboard disappears for everyone who rejoined to the server

**Comment by Puharesource** [comment]
This should be fixed with the latest changes made. Keep an eye out for version 2.1.7
