### ISSUE TITLE
PlaceHolder Not working

### ISSUE THREAD

**Issue by ToxicGR** [Puharesource/TitleManager#255]
**Describe the bug**
After a google search i found out that the placeholder for how many bungee players are online is this %{bungeecord-online} but is not working . I have tried this {bungeecord-online}, this {placeholderapi_bungeecord-online}, this %bungeecord-online% Nothing  seems to work. if you can me that will be great thank you. Also i have donwloaded the papi expansion for player and bungee.

**To Reproduce**
1. Go to Config and just add the placeholder to the header or the footer.

**Expected behavior**
I expected the placeholder to show how many players are active in the bungee

**Server information:**
 - TitleManager version: [ 2.1.5]
 - Spigot version: [Spigot 1.8.8]

**Comment by Puharesource** [comment]
You need to set `using-bungeecord` to `true` in the config.
