### ISSUE TITLE
Title manager keeps disappearing when rejoining ! Plugin needs more dev work

### ISSUE THREAD

**Issue by preppy420** [Puharesource/TitleManager#256]
**Describe the bug**
Title manager keeps disappearing when rejoining ! Plugin needs more dev work
**To Reproduce**

**Expected behavior**

**Screenshots**

**Stacktrace / Error**
Please check the console for any errors that TitleManager might be producing.

**Server information:**
 - TitleManager version: latest
PaperSpigot 1.15

**Additional context**

**Comment by Puharesource** [comment]
The latest changes should fix these issues. Keep an eye out for the 2.1.7 release
