### ISSUE TITLE
Scoreboard points

### ISSUE THREAD

**Issue by vspres** [Puharesource/TitleManager#258]
Hi I really liked the plugin. But I have a question, does the plug-in with points, for example, every time a monster kills get points
(Like another kind of money)

Sorry about the English

**Comment by zuhir** [comment]
TitleManager is for Titles, scoreboard, tab and automessages, not for that. If you want receive something when you kill mobs use another plugin and if that plugin has PlaceHolderAPI support you can put placeholders in TitleManager's config

**Comment by Puharesource** [comment]
Exactly what @zuhir said.
