### ISSUE TITLE
LuckPerms group displayname

### ISSUE THREAD

**Issue by zuhir** [Puharesource/TitleManager#260]
**Describe the bug**
If you have LuckPerms and you set colored displayname for group (ex /lp group admin setdisplayname "&cAdmin") TitleManager shows "&cAdmin" instead of "Admin" in red

**Screenshots**
![asd](https://user-images.githubusercontent.com/17429859/79403641-da5a5900-7f65-11ea-847b-eaf053878766.png)

**Server information:**
 - TitleManager version: 2.1.5 (because v2.1.6 is bugged)
 - Spigot version: 1.8.8

**Comment by Puharesource** [comment]
This will be fixed in version 2.1.8
