### ISSUE TITLE
TitleManager 2.1.7 crashes server with error "Could not pass player join event to TitleManager v2.1.7"

### ISSUE THREAD

**Issue by doggo4242** [Puharesource/TitleManager#262]
**Describe the bug**
TitleManager 2.1.7 crashes server with error "Could not pass player join event to TitleManager v2.1.7"

**To Reproduce**
Start PaperMC 1.15.2 server with version 2.1.7, then join server.
**Expected behavior**
TitleManager should not crash server and should function as normal

**Screenshots**

**Stacktrace / Error**
[https://pastebin.com/FwyYCFb4](https://pastebin.com/FwyYCFb4)
**Server information:**
 - TitleManager version: 2.1.7
 - Spigot version: PaperMC 1.15.2

**Additional context**
On the few occasions that the server does not crash immediately, one can see that the footer does not show up in the tab menu

**Comment by Puharesource** [comment]
It's caused by the TPS placeholder now working properly on Paper. I've made the change to the code in 0bbb56d691d615a83aa269c4eacf4126e1943a92 and it'll be ready in the next release (2.2.0) very soon.
