### ISSUE TITLE
API Give Scoreboard Not Functioning

### ISSUE THREAD

**Issue by zachduda** [Puharesource/TitleManager#264]
**Describe the bug**
When calling the API instance for "giveScoreboard(Player)" it seems to not work. When trying to call "removeScoreboard(Player)" however, it does indeed remove the scoreboard.

**Expected behavior**
The scoreboard is supposed to appear when calling giveScoreboard(Player)

**Stacktrace / Error**
Interestingly enough, there are no errors thrown.

**Server information:**
 - TitleManager version: v2.1.7
 - Spigot version: PaperSpigot 1.15.2

**Additional context**
This is only a minor API related issue. Commands and everything else function exactly as intended. :)

**Comment by Puharesource** [comment]
Give scoreboard gives you a blank scoreboard to work with, there's currently no way of given the in-built scoreboard that TitleManager provides. I can however add a way of giving the default scoreboard, if you're currently writing a plugin that's supposed to toggle the scoreboard the one that TitleManager provides

**Comment by zachduda** [comment]
Oh my bad! An API method to toggle the default scoreboard would be great. :)

**Comment by Puharesource** [comment]
This has been added in 412f8de and will be ready when the next version is released (2.2.0). You can already check out the new API methods in the JavaDocs.

TitleManagerAPI#giveDefaultScoreboard In the JavaDoc will have the effect you're looking for, you might have to purge your browser cache or open a different browser to see the changes. (At least I had to)

**Comment by zachduda** [comment]
Perfect! Thanks so much. 🙂
