### ISSUE TITLE
Scoreboard resets if you toggle it off and on.

### ISSUE THREAD

**Issue by Sollembum78** [Puharesource/TitleManager#265]
**Describe the bug**
I set custom values to be displayed in scoreboard, but some players may want to turn it off if it's annoying.. So they will use /tm sb toggle. When they toggle it back on - they see default values "my server, player, ping, server time" instead of my custom settings. Other players continue to see normal stuff.
**To Reproduce**
1. Set any non-default values for scoreboard part.
2. Join server and use /tm sb toggle to turn it off
3. Use /tm sb toggle again to turn it on
4. You will see default scoreboard instead of what is in the config

**Expected behavior**
I expect it to return to style set in config

**Screenshots**
https://ibb.co/M95khY1
https://ibb.co/D5WWm9x

**Stacktrace / Error**
No errors in log/console

**Server information:**
 - TitleManager version: 2.1.7
 - Spigot version: PaperSpigot 1.15.2

**Additional context**

**Comment by Puharesource** [comment]
Oh that's strange, it's probably fixed by a restart of the server though right?
I'll be sure to fix this in the next release though ;)

**Comment by Sollembum78** [comment]
Yes, it also fixes if player re-joins or I do /tm reload, but as long as player is online he will see default lines. Waiting for new release then :)

**Comment by Puharesource** [comment]
This has been added in 412f8deb4c0b8c068128fde08b92c050c0f90744 and will be ready when the next version is released (2.2.0). You can already check out the new API methods in the JavaDocs.

TitleManagerAPI#giveDefaultScoreboard In the JavaDoc will have the effect you're looking for, you might have to purge your browser cache or open a different browser to see the changes. (At least I had to)

**Comment by Puharesource** [comment]
This is fixed in the upcoming version (The code has been added, just fixing other things up and it'll be ready some time probably tomorrow!)
