### ISSUE TITLE
Join Subtitle becomes the same as the Join Title in config.yml

### ISSUE THREAD

**Issue by tommyteschner** [Puharesource/TitleManager#266]
**Describe the bug**
When you make the title on join in the config.yml for example, "&7Welcome Back" and you make the subtitle on join "&3to &b&lServer&7!" and reload the plugin/restart when you join it shows "&7Welcome Back" for the title and subtitle. Screenshots below.

**To Reproduce**
1. Make the join title one thing
2. Make the join subtitle another
3. Join the Server

**Expected behavior**
It is supposed to not copy the title to the subtitle.

**Screenshots**
Attached.
![2020-04-21_16 13 09](https://user-images.githubusercontent.com/63168493/79923789-2afd0680-83eb-11ea-81bb-99500e207075.png)
![Capture](https://user-images.githubusercontent.com/63168493/79923803-318b7e00-83eb-11ea-94db-7b1b0647129b.PNG)

**Stacktrace / Error**
No errors.

**Server information:**
 - TitleManager version: 2.2.1
 - Spigot version: 1.8.8

**Additional context**
Please fix fast! I love your plugin <3.

**Comment by Puharesource** [comment]
I'm off to bed now, but it'll be the first fix tomorrow!
