### ISSUE TITLE
%{tps} feature

### ISSUE THREAD

**Issue by Tikkle** [Puharesource/TitleManager#268]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
A placeholder for server TPS. It would be greatly appreciated if you could add this :)

**Comment by Puharesource** [comment]
That actually already works, I just forgot to add it to the wiki ;)

**Comment by aeonlamb** [comment]
The placeholder doesn't seem to work in the tab list. In fact, it completely freezes all other dynamic placeholders/animations on the tablist header/footer when used there.
