### ISSUE TITLE
Broken Subtitle

### ISSUE THREAD

**Issue by Midnight9746** [Puharesource/TitleManager#269]
**Describe the bug**
On 1.15.2, (PaperMC), I've noticed that when you do "/tm broadcast <message>", it works, but when you add the "\n<message 2>", the message no longer sends.

**To Reproduce**
1. Use Latest 1.15.2 MC Paper (May be a bug on Spigot too)
2. /tm broadcast message \n submessage
3. Title should not send.

**Expected behavior**
The title sends the message properly.

**Stacktrace / Error**
No error, it says it sent the message without issues.

**Server information:**
 - TitleManager version: 2.2.7
 - PaperSpigot 1.15.2
 - Using Version 2.1.6 (The last version we used) works with the subtitle.

**Comment by Bricec6** [comment]
Same for me version paper version 350 (1.15.2), i use titlemanager 2.2.7
and {nl} or %nl% , not work

![image](https://user-images.githubusercontent.com/51750055/84590166-73a5ce80-ae34-11ea-8657-18b1e9305a20.png)

**Comment by DokanBoy** [comment]
If you use <nl>, the message simply will not appear to the players. There will be no errors in the console and the team handler will realize that I am sending 2 lines.

**Comment by Bricec6** [comment]
up up up

**Comment by DokanBoy** [comment]
@Puharesource

**Comment by Puharesource** [comment]
@Bricec6 It's `<nl>` and `\n` and not `%nl%` or `{nl}`
