### ISSUE TITLE
Update Alerts & Sub-Titles

### ISSUE THREAD

**Issue by UntoldFury** [Puharesource/TitleManager#27]
First off, I have to say I am absolutely LOVING this plugin, and I love how often it is being updated and fixed. However, it seems like whenever I don't check the plugin page, I am about 2-3 verisons behind, and I didn't even notice. That's why I think it would be a good idea to add an in-game announcement that tells ops that an update is available for the plugin, and a link on where to find it. It would definitely help keeping updated on this plugin.

I also think it would be nice to have a way to broadcast something when you do /tm bc. When you do /tm bc, it only shows the big title line. Maybe you could make it when you do /n it will move to the smaller sub-title?

Like I said, really enjoying this plugin! Thanks for all your hard work!
~UntoldFury

**Comment by Puharesource** [comment]
I've been thinking of implementing a way of telling server administrators about updates and this will be an update in the future :)

Anyways, to the `/tm bc` part, you can split a message by using `<nl>` or `{nl}` within your message :)

E.g. `/tm bc This is the first line<nl>This is the second line`

**Comment by Puharesource** [comment]
8439437d331ac41d30cb547c51a5585026eb59bd Automatic update notifications have been added :) and will be available next time the plugin updates.
