### ISSUE TITLE
I have a question for you

### ISSUE THREAD

**Issue by vspres** [Puharesource/TitleManager#271]
I have several worlds on one server, and in all the worlds the scoreboard works, can I do for example that the nether scoreboard will not work? I choose which worlds I want the scoreboard to work on.
Anyway I really liked your plugin and it really helps me, thank you very much

**Comment by cantercrow** [comment]
Hi,

I  really like Title Manager but would be nice be be able to choose what worlds each title appears in.

Thanks

**Comment by vspres** [comment]
how can i do this ?

**Comment by Puharesource** [comment]
@vspres @cantercrow There's a `disabled-worlds` field in the config, just add the worlds you don't want the sidebar in and it won't show up in those worlds.
