### ISSUE TITLE
Lag in player join | Event

### ISSUE THREAD

**Issue by JavituRec** [Puharesource/TitleManager#275]
**Describe the bug**
When users enter the server, there are tps spikes caused by the title manager playerjoinevent event.

plugin version: 2.2.7
Server version 1.15.2

Capture:
![titleee](https://user-images.githubusercontent.com/10663192/83744736-de991d80-a65c-11ea-9da2-7a9fdbaf3ac6.PNG)

**Comment by JavituRec** [comment]
I still have this problem. Any way to fix it? It only happens at the players' join.

![laggggg](https://user-images.githubusercontent.com/10663192/84401182-432b1e00-ac03-11ea-85e8-bfc91022173c.JPG)

**Comment by Puharesource** [comment]
I'll need the full timings report to be able to use it for anything, as it seems to me that your timings hadn't run for very long
