### ISSUE TITLE
PAPI bug

### ISSUE THREAD

**Issue by PineAppleGrits** [Puharesource/TitleManager#277]
**Describe the bug**

**To Reproduce**
Use PlaceHolders Api into titlemanager

**Expected behavior**
I can't use the placeholders and i dont know why

**Screenshots**
![image](https://user-images.githubusercontent.com/66481194/83888892-d4d8ee00-a720-11ea-8e26-45445bf20b77.png)
![image](https://user-images.githubusercontent.com/66481194/83891477-98f35800-a723-11ea-9fc2-b47faf6dca82.png)

**Stacktrace / Error**
Please check the console for any errors that TitleManager might be producing.
---none_
**Server information:**
 - TitleManager version: 2.2.7
 - Spigot 1.8

Just that. I can't use placeholders api andi dont know why.

**Comment by PineAppleGrits** [comment]
I need help and solve this the fastest posible, thanks -

**Comment by Puharesource** [comment]
You need to download the needed extensions for PlaceholderAPI using `/papi ecloud` please refer to PlaceholderAPI wiki instead
