### ISSUE TITLE
Deathcount

### ISSUE THREAD

**Issue by Wukkel** [Puharesource/TitleManager#278]
So the scoreboard on the right is there like a thing to add deathcount? if not this could be quite cool
{deathcount} or something

**Comment by DayTrix03** [comment]
check statistics placeholder.

**Comment by DayTrix03** [comment]
{player_deaths}
and
{player_kills}

**Comment by DayTrix03** [comment]
reminder: these are PLACEHOLDERS not built-in from TitleManager plugin. I use these placeholders in my faction server.

**Comment by Puharesource** [comment]
You can achieve this by using PlaceholderAPI.
