### ISSUE TITLE
TitleManager error

### ISSUE THREAD

**Issue by DayTrix03** [Puharesource/TitleManager#279]
**Describe the bug**
Error when starting server

**To Reproduce**

**Expected behavior**
Should start perfectly like before

**Screenshots**

**Stacktrace / Error**
io.puharesource.mc.titlemanager.shaded.kotlin.NotImplementedError: An operation is not implemented.

**Server information:**
 - TitleManager version: 2.2.7
 - Spigot version: 1.15.2

**Additional context**
TitleManager was working pefectly before.

**Comment by dnyferguson** [comment]
Having the same issue

stacktrace: https://pastebin.com/tDY2qaVX

Server info:
- Plugin: Titlemanager v2.2.6
- Server jar: Tuinity 1.15.2
- Java: Java 8 Oracle
