### ISSUE TITLE
Per world support

### ISSUE THREAD

**Issue by Sinxwins** [Puharesource/TitleManager#28]
So sorry if my name was not the-same with spigot i change it because the name was already register

**Comment by Wundero** [comment]
This should be completed if puharesource merges #49, hopefully what you requested is covered.

**Comment by Puharesource** [comment]
This will be done once I have enough time to look over the changes and fix possible issues.

**Comment by Puharesource** [comment]
Fixed by commit 03bcec42a15824a55a4306d2e9920285fc73fb32
