### ISSUE TITLE
Titlemanager

### ISSUE THREAD

**Issue by CozyLeprechaun94** [Puharesource/TitleManager#281]
**Describe the bug**
Titlemanager isn't displaying luckperms.prefix placeholder correctly.

**Screenshots**
https://imgur.com/a/4q2Ukag

**Server information:**
 - TitleManager version: [Example:. 2.1.5]
 - Spigot version: [Example: Spigot 1.14.4 or PaperSpigot 1.12]

**Comment by Puharesource** [comment]
I'll have a look at it

**Comment by Puharesource** [comment]
Those color codes only work for Minecraft version 1.16 and above
