### ISSUE TITLE
Gradients conflcit with %{online} placeholder

### ISSUE THREAD

**Issue by Projecki** [Puharesource/TitleManager#282]
**Describe the bug**
%{online} flickers, does not always show player count when using gradients.

**To Reproduce**
Attempt to add %{online} placeholder to player list like such:
"%{gradient:[#ff99ff,#ff33ff,#e600e6]%{online} creators} &fon this realm"

**Expected behavior**
Placeholders function properly

**Screenshots**
https://cdn.discordapp.com/attachments/708238845338189918/736063648765837433/unknown.png

**Stacktrace / Error**
none

**Server information:**
TM 2.3.0
PaperSpigot 1.16.1

**Comment by Puharesource** [comment]
You need to cancel the `}` by adding a `\` in front of it, due to the fact that otherwise the gradient things that it needs to end when the online placeholder ends.

Here's an example:
`%{gradient:[#ff99ff,#ff33ff,#e600e6]%{online\} creators} &fon this realm`
