### ISSUE TITLE
Strange colors

### ISSUE THREAD

**Issue by XXY233** [Puharesource/TitleManager#283]
**Describe the bug**
The color in the scoreboard is too different from the actual color.

**Expected behavior**
The color should always be the color in the configuration file

**Screenshots**
![20200724174057](https://user-images.githubusercontent.com/46647646/88379103-e3fd2380-cdd4-11ea-9c22-a2548641dbb5.jpg)
![20200724173959](https://user-images.githubusercontent.com/46647646/88379105-e495ba00-cdd4-11ea-944a-711f35c9c3db.jpg)

**Server information:**
 - TitleManager version: 2.3.0
 - Spigot version: PaperSpigot 1.16.1

**Additional context**
Both colors in the screenshot should be blue.

**Comment by Puharesource** [comment]
Yeah, the colors on the Scoreboard seems to be messed up, I'll have a look at it
