### ISSUE TITLE
%{online} ignores vanished players

### ISSUE THREAD

**Issue by Bloodlex** [Puharesource/TitleManager#284]
**Describe the bug**
Both plugins EssentialsX and SuperVanish vanish mode are ignored by this placeholder and indicating vanished player by counting a player into the number.

**To Reproduce**
1. Install EssentialsX or SuperVanish
2. Go into vanish mode
3. Check the placeholder
4. The placeholder shows a number including a vanished player

**Expected behavior**
Vanished player should not be visible in players online

**Screenshots**
[https://imgur.com/a/WkwV8s7](https://imgur.com/a/WkwV8s7)

**Stacktrace / Error**
No stacktrace

**Server information:**
 - TitleManager version: 2.3.0
 - Spigot version: Paper-380 (MC 1.15.2)

**Additional context**

**Comment by baailey** [comment]
Use `%{safe-online}` instead of `{online}`

**Comment by Bloodlex** [comment]
Thanks!
