### ISSUE TITLE
since 2.3.1 lines that are same do not get hidden anymore

### ISSUE THREAD

**Issue by GovindasOM** [Puharesource/TitleManager#287]
**Describe the bug**
lines that are the same get hidden and only one line is shown usually, but since 2.3.1 they are all shown even if they're same. the automatic hiding of same lines was super useful to me, so I'd love that to be back.

**To Reproduce**
1. Set two lines on the scoreboard as the same
2. observe them both being displayed instead of only one (like how it was in older version of TitleManager)
**Expected behavior**
Lines that are the same would get hidden and only one be shown.

**Screenshots**
![paveikslas](https://user-images.githubusercontent.com/16716020/88648148-5f115300-d0cf-11ea-8657-c5ee44af8896.png)

**Stacktrace / Error**
None

**Server information:**
 - TitleManager version: [Example:. 2.3.1]
 - Spigot version: [Paper 1.12.2]

**Additional context**
None

**Comment by Govindass** [comment]
I just didn't get any reply :(

**Comment by Govindass** [comment]
keep it open

**Comment by Govindass** [comment]
keep it open

**Comment by Puharesource** [comment]
Hey sorry that I've been MIA. What's the use of it? This was previously caused by limitations in Minecraft, which I've now managed to circumvent. It would take some time to implement something similar.

If you're just trying to remove lines, you can simple remove the lines from the config. :)

**Comment by Govindass** [comment]
> Hey sorry that I've been MIA. What's the use of it? This was previously caused by limitations in Minecraft, which I've now managed to circumvent. It would take some time to implement something similar.
> 
> If you're just trying to remove lines, you can simple remove the lines from the config. :) 

I use it for easier handling of dynamic lines count, so a player gets a diamond in game - it appears on his scoreboard as a new line (which was empty, thus not displayed before) I use scoreboard as a replacement for inventory

**Comment by Puharesource** [comment]
Ah, that makes sense. I guess I could make a config options, that would hide completely empty lines
