### ISSUE TITLE
Enjin's Donationcraft conflicts with the <nl> delimiter

### ISSUE THREAD

**Issue by wilsondc15** [Puharesource/TitleManager#29]
Enjin's Donationcraft conflicts with the <nl> delimiter use in commands. This affects many people because many owners want to be able to auto announce using TitleManager through Donationcraft that a player just donated. Donationcraft auto removes all < and > in commands before being run so when there is a message that is long and needs a second line, it runs the command with no delimiter so it all come on one title broadcast covering the whole screen!

Solution:
Add \n as a delimiter as well. Enjin does not block \'s.

**Comment by Puharesource** [comment]
You have been able to use {nl} for ages, however, the next version will both support <nl>, {nl} and %nl%
