### ISSUE TITLE
Animations kicks players on join

### ISSUE THREAD

**Issue by RidaThe94** [Puharesource/TitleManager#297]
**Describe the bug**
Getting kicked on join if animation was used

**To Reproduce**
1. Have any animation on the scoreboard such as ${right-to-left} or ${shine:[0;25;0][&3&l;&b&l]My text}
2. Join the server

**Expected behavior**
Not getting kicked and the animation works

**Screenshots**
N/A

**Stacktrace / Error**
There is no stacktrace but I get this warning in console
```[01:51:17 WARN]: [TitleManager] No script engine found. Consider adding Nashorn or GraalVM to be able to create custom animation scripts. (This warning can be ignored)```

**Server information:**
 - TitleManager version: 2.3.1
 - Spigot version: Tunity 1.16.2

**Comment by RidaThe94** [comment]
Version 2.3.0 works fine

**Comment by RidaThe94** [comment]
still not fixed

**Comment by alfredcort** [comment]
"The server you were previously on went down, you have been connected to a fallback server"

This is what happens when players try to join the server with Titlemanger from the lobby (bungee). When removing Titlemanager they can join without issues. Very strange.

**Comment by RidaThe94** [comment]
not fixed yet

**Comment by Puharesource** [comment]
Should be fixed in 7e1f576ab15b1d7009c0ca89edc96864a4741ea4
