### ISSUE TITLE
title manager causing a join loop

### ISSUE THREAD

**Issue by Ytsharpbelt636** [Puharesource/TitleManager#299]
i had title manager and updated the server to 1.16.2  i updated title manager aswell and i tried to join and i was in a continuous join cycle im not sure why but i no longer use this plugin i dont need support but i thought you should know

**Comment by Chezzer-ub** [comment]
I am getting this aswell, but on a bungee setup. It is kicking any player who joins with "Disconnected"

**Comment by Chezzer-ub** [comment]
Damn this is really inactive, it's full out not working on spigot 1.16.3 and this issue is a month old?

**Comment by Ytsharpbelt636** [comment]
> Damn this is really inactive, it's full out not working on spigot 1.16.3 and this issue is a month old?

i dont use title manager no more cus it wouldnt work on 1.16.3
