### ISSUE TITLE
Use of TPS Placeholder seems to break animation

### ISSUE THREAD

**Issue by kn1gh7h4wk** [Puharesource/TitleManager#303]
Hello,

I downloaded TM today and added the ${tps} placeholder in the footer section. After reload, and later reboot, the left-right and right-animations, as well as the world clock, stopped/froze. Another reload will update the world clock, but only to the time of the reload. Removing the TPS placeholder seems to fix the animations/world clock.

My primary reason for getting TM was so that I could display the TPS in the scoreboard. But animations would be nice.

PaperMCS 1.16.4

**Comment by 0x5c** [comment]
I can confirm getting the same behaviour. The TPS placeholder causes the footer (or header) to stop updating.


PaperMC `git-Paper-399` (1.16.4)
TitleManager `2.3.1`

**Comment by 0x5c** [comment]
Not fixed so no reason to close it

**Comment by Puharesource** [comment]
Should be fixed in a2496bd6ba686d65d1967cdf48fc3b2b9f6c7882
