### ISSUE TITLE
Team tm-sb-0 already exists in this scoreboard

### ISSUE THREAD

**Issue by xSorch** [Puharesource/TitleManager#304]
Describe the bug
Unable to enter the server from BungeeCord

Stacktrace / Error
https://paste.helpch.at/abajijefen.apache

Server information:

TitleManager version: 2.3.1
Spigot version: PaperSpigot 1.16.2

**Comment by xSorch** [comment]
All other versions are fine apart from 2.3.1. So I am currently using 2.3.0

**Comment by RedstoneFuture** [comment]
I use `Waterfall-Bootstrap:1.16-R0.4 #388` with TitelManager 2.3.1 and PaperMC 1.13.2 and haven't a problem.

**Comment by Maescool** [comment]
Bug introduced here:
https://github.com/Puharesource/TitleManager/blame/0c3ca4730d3bdc50561db9961ada156242d802f5/src/main/kotlin/io/puharesource/mc/titlemanager/internal/services/features/ScoreboardServiceSpigot.kt#L196

**Comment by Maescool** [comment]
#305 and #307 seem to be related to the same bug

**Comment by PremiereSetups** [comment]
> with TitelManager 2.3.1 and PaperMC 1.13.2 and haven't a p

Tried the version you said. Got the same issue OP was having.

**Comment by Puharesource** [comment]
Fixed in 7e1f576ab15b1d7009c0ca89edc96864a4741ea4
