### ISSUE TITLE
Title Manager kicking the player for fallback

### ISSUE THREAD

**Issue by Khosraw** [Puharesource/TitleManager#305]
**Describe the bug**
Once updating the plugin from I believe 2.2.7 to 2.3.1, it ends up kicking players for fallback.

**To Reproduce**
1. Replace a title manager version 2.2.7 to 2.3.1
2. Run it on bungeecord
3. Restart the server
4. Get kicked for fallback

I am not entirely sure whether this will happen for others as well.

**Expected behavior**
I should be able to join the server like normal without getting kicked for fallback.

**Screenshots**
![image](https://user-images.githubusercontent.com/53713571/100912056-a05aaa80-3495-11eb-827d-8b16c689daa5.png)

**Stacktrace / Error**
No errors in the console.
**Server information:**
 - TitleManager version 2.3.1
 - Purpur version git-Purpur-606 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by RedstoneFuture** [comment]
I can't replicate this problem with version 2.3.1 on PaperMC 1.16.4 and BungeeCord.

**Comment by morgan2233** [comment]
I have the same problem. Came to here to report it.

I am running the latest version of the plugin on PaperMC 1.16.4 though Waterfall (fork of BungeeCord) and my server is running Headless Java 11. 

Whenever I connect, I get the same error as shown by the creator of this issue. No error in console.

**Comment by morgan2233** [comment]
> I can't replicate this problem with version 2.3.1 on PaperMC 1.16.4 and BungeeCord.

I tried 2.3.0 and the issues went away. The issue is only present on 2.3.1 for me.

**Comment by Puharesource** [comment]
Should be fixed in 7e1f576ab15b1d7009c0ca89edc96864a4741ea4
