### ISSUE TITLE
Option to delay welcome title sending by a certain amount of ticks.

### ISSUE THREAD

**Issue by mibby** [Puharesource/TitleManager#306]
Paper dev 332 (Spigot 1.16.4)
TitleManager compiled as of commit https://github.com/Puharesource/TitleManager/commit/0c3ca4730d3bdc50561db9961ada156242d802f5

**Is your feature request related to a problem? Please describe.**
@Puharesource Would it be possible to implement an option to delay sending the welcome-title by x amount of ticks? I use a placeholder in the title to display the player's displayname. However the player title seems to get sent before users are fully loaded in, before loading their group prefix and nick. This is causing their vanilla name without color to be sent to the title display.

**Describe the solution you'd like**
An option to delay sending the login welcome title by a few ticks. Generally I've delayed my login join message by 5 ticks so it displays color properly on join.

**Additional context**
```
############################################################
# +------------------------------------------------------+ #
# |                    Welcome Title                     | #
# +------------------------------------------------------+ #
############################################################

# Sets the title that is sent to the player when they join the server.

welcome-title:

  # Toggles this feature.
  enabled: true

  # The title displayed at the very top of the scoreboard
  # WARNING! (1.12 or below ONLY) The title must consist of 32 or less characters (this includes color codes)
  title: '&f&l» Ex&b&lample &f&l«'

  # The subtitle shown.
  subtitle: '&bWelcome back, %{DISPLAYNAME}'

  # The time it takes for the title to fade into the screen. (In ticks)
  fade-in: 30

  # The time it takes for the title to stay on the screen. (In ticks)
  stay: 60

  # The time it takes for the title to fade out of the screen. (In ticks)
  fade-out: 30

  # The message shown when the player joins the server for the first time.
  first-join:

    # The title shown.
    title: '&f&l» Ex&b&lample &f&l«'

    # The subtitle shown.
    subtitle: '&bWelcome, %{DISPLAYNAME}'
    ```

**Comment by mibby** [comment]
Bad bot.

**Comment by Puharesource** [comment]
Yes this should definitely be possible! I'll keep it in mind in my next release.

**Comment by mibby** [comment]
Bad bot.

**Comment by Puharesource** [comment]
Added in the least release :)
