### ISSUE TITLE
%{balance} Placeholder doesnt work

### ISSUE THREAD

**Issue by Mawobi** [Puharesource/TitleManager#326]
**Describe the bug**
Placeholder %{balance} doesnt work in Actionbar, when defined in Config.
No Error in Chat or console. No output in Actionbar. Just happens nothing.
When I define in Actionbar the text "test %{balance}" is also no output. The "test" wont be given out.

**Server information:**
 - TitleManager version: 2.3.1
 - Spigot version: 1.16.5

**Comment by Puharesource** [comment]
You need to have Vault installed alongside a valid Economy plugin.
