### ISSUE TITLE
Java an Spigot support

### ISSUE THREAD

**Issue by MrTokyo12345** [Puharesource/TitleManager#327]
Please add Java 11 and spigot 1.16.5 support

**Comment by markaabo** [comment]
Would love Java 11 support, it seems to have broken stuff like $shine animation

**Comment by Puharesource** [comment]
Are there other features that are broken, than the animations?

**Comment by markaabo** [comment]
> Are there other features that are broken, than the animations?

It seems to be glitching the tab menu, like players keep switching places even tho no new players join or anyone leaves, its like jittering names all over :/

**Comment by Puharesource** [comment]
> > Are there other features that are broken, than the animations?
> 
> It seems to be glitching the tab menu, like players keep switching places even tho no new players join or anyone leaves, its like jittering names all over :/

That has nothing to do with TitleManager as TitleManager never touches the players in the Player List, just the header and footer.
