### ISSUE TITLE
Not working on my server but work on my local server :S

### ISSUE THREAD

**Issue by TriiNoxYs** [Puharesource/TitleManager#34]
Hi,
When i put the plugin on my server, there is an error at line 32 of SubBroadcast.java (http://prntscr.com/7dglg5 error)
can you fix it please ?

**Comment by Puharesource** [comment]
Please tell me what version of TitleManager you're using, what version of Spigot you're using and the entire error message, rather than a picture (preferably the entire server log)

**Comment by TriiNoxYs** [comment]
I'm using Spigot 1.8.6 and TitleManager 1.5.4.
Full log: http://pastebin.com/dznRC7pg (The MineOS panel doesn't give me more)

**Comment by Puharesource** [comment]
Go inside of the logs folder and download the latest.log file.

**Comment by TriiNoxYs** [comment]
Content of latest.log: http://pastebin.com/bUcB0wet

**Comment by Puharesource** [comment]
Is that all of it? Because, when hitting that error it should technically also have an issue when loading the plugin.

Also, does this only happen with /tm bc? Or also with other commands?

**Comment by TriiNoxYs** [comment]
Yep, i've copied ALL the latest.log file. 
And the error is only hapening whith /tm bc and /tm amsg  (all the commands wich send Titles)

**Comment by TriiNoxYs** [comment]
Ok, i've found the entiere log: http://pastebin.com/bhbmm3cD

**Comment by TriiNoxYs** [comment]
I've solved my problem ! It's not comming from your plugin ! 
The config.yml had 664 FTP rights, i've puted it on 755 and wall works !
Thank you for putting me on the right track !

And REALLY GOOD plugin, keep it up ! ;)

**Comment by Puharesource** [comment]
I'm glad that you figured out what the issue was, and that you like my plugin ^^
