### ISSUE TITLE
Bungeecord TM Broadcast

### ISSUE THREAD

**Issue by YepImRobbie** [Puharesource/TitleManager#36]
Hi, I have an exciting idea to enhance the titlemanager as it slides further into bungeecord support, a feature that will enable the ability to do /tm bc, yet it will pop-up on all bungeecord servers, if this isn't possible, no worries. :)

**Comment by Puharesource** [comment]
Yeah, I've thought about that as well ^^

**Comment by JustBru00** [comment]
I would love to see this implemented.

**Comment by Wundero** [comment]
I have written the implementation for this, but I am holding off on a PR until some other PR's are finished. It will still take some time after that as Puharesource has to review and compile the plugin, but hopefully that will be soon.

**Comment by Wundero** [comment]
I have submitted the PR and Puharesource will be reviewing it this week.
