### ISSUE TITLE
Remove this warning, please..

### ISSUE THREAD

**Issue by molor** [Puharesource/TitleManager#360]
**Describe the bug**
"problem still exists (Java 11)" /2/
See https://github.com/Puharesource/TitleManager/issues/191

**To Reproduce**
Run the server.

**Expected behavior**
No warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/19989717/115528186-7bc36b80-a29a-11eb-8031-dd84afdec41e.png)

**Server information:**
 - TitleManager version: 2.3.3
 - Paper version: git-Paper-593 (MC: 1.16.5)

**Comment by molor** [comment]
@Puharesource, in Java 16 there are "No script engine found.". Could you please hide this warning? I haven't used animations and I don't plan to, so a single yellow warning line in entire console from TitleManager is very distracting.. or at lease make it Level.INFO, not a warning :c

**Comment by mibby** [comment]
Also can confirm receiving the same issue as of Java 16 & TitleManager v2.3.3.

```
[14:03:00] [Server thread/INFO]: [TitleManager] Enabling TitleManager v2.3.3
[14:03:00] [Server thread/WARN]: [TitleManager] No script engine found. Consider adding Nashorn or GraalVM to be able to create custom animation scripts. (This warning can be ignored)
```
