### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by Malachiel87** [Puharesource/TitleManager#376]
**Describe the bug**
Can you kindy add 1.17 support? :)

**Stacktrace / Error**
https://pastebin.com/cVHBqP94

**Server information:**
 - TitleManager version: [Example:. 2.3.0]
 - Spigot version: [Example: Spigot 1.14.4 or PaperSpigot 1.12] Spigot 1.17

**Additional context**
Thank you! <3

**Comment by Puharesource** [comment]
Just released a new update ;)
