### ISSUE TITLE
Config resets

### ISSUE THREAD

**Issue by truxtonl** [Puharesource/TitleManager#38]
Whenever I edit the config, it seems to reset itself whenever I stop then restart the server, making no changes at all.

**Comment by Puharesource** [comment]
Could you please give me some more information?

Like Spigot version, TitleManager version and OS.

Also, have you checked your file permissions? Since, this seems like a file permission error more than anything.

**Comment by Puharesource** [comment]
No response...

This was most likely due to the user's file permissions being messed up.
