### ISSUE TITLE
Could not pass PlayerJoinEvent while displaying scoreboard

### ISSUE THREAD

**Issue by Bloodlex** [Puharesource/TitleManager#381]
**Describe the bug**
An exception after player enters and he should see the scoreboard.

**To Reproduce**
1. Configure scoreboard
2. Enter the server with enabled scoreboard
3. See exception

**Expected behavior**
A player should see the scoreboard.

**Stacktrace / Error**

22.06 17:23:40 [Server] ERROR Could not pass event PlayerJoinEvent to TitleManager v2.3.4
22.06 17:23:40 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class io.puharesource.mc.titlemanager.internal.reflections.ChatSerializer
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.setTitleWithoutLimit(ScoreboardHandler.kt:105) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.setTitle(ScoreboardHandler.kt:35) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.<init>(ScoreboardHandler.kt:42) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.<init>(ScoreboardHandler.kt:15) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.giveScoreboard(ScoreboardServiceSpigot.kt:61) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.giveDefaultScoreboard(ScoreboardServiceSpigot.kt:68) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.toggleScoreboardInWorld(ScoreboardServiceSpigot.kt:234) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetScoreboard$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetScoreboard$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[?:?]
22.06 17:23:40 [Server] INFO at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[?:?]
22.06 17:23:40 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:315) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:163) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1593) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1060]
22.06 17:23:40 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]

**Server information:**
 - TitleManager version: 2.3.4
 - Spigot version: This server is running Purpur version git-Purpur-1060 (MC: 1.16.5)

**Additional context**
Config:
[https://pastebin.com/3PfQjmSf](https://pastebin.com/3PfQjmSf)

**Comment by Puharesource** [comment]
It seems like it's an issue with using 1.16 or below, I'll fix it in the next release. Until then please downgrade TitleManager to 2.3.3 or the server to Minecraft 1.17

**Comment by Bloodlex** [comment]
> It seems like it's an issue with using 1.16 or below, I'll fix it in the next release. Until then please downgrade TitleManager to 2.3.3 or the server to Minecraft 1.17

Thank you very much 🙂
