### ISSUE TITLE
1.16.5 Paper Server JoinEvent Error

### ISSUE THREAD

**Issue by Hitosherizu** [Puharesource/TitleManager#389]
**Describe the bug**
Scoreboard does not appear on 1.16.5 Paper server with 2.3.4

**To Reproduce**
Latest 1.16.5 Paper server
Install Titlemanager 2.3.4
Join Server
See error

**Expected behavior**
Scoreboard to show up, no joinevent

**Stacktrace / Error**
https://paste.ee/p/czkd0 Includes Plugin List, Paper Version, and Full error

**Server information:**
 - TitleManager version: 2.3.4
 - Spigot version: Paper 1.16.5, 780

**Additional context**
Works fine on previous build 2.3.3 for TitleManager.

**Comment by MrmaximoExcssum** [comment]
FIX your plugin man nothing works!!!

**Comment by thuan782004** [comment]
same error but in purpur 1.17 and no error log appear!
