### ISSUE TITLE
Placeholders not working [API] [1.17.1]

### ISSUE THREAD

**Issue by EnriqueGF** [Puharesource/TitleManager#398]
Hello,

Through API im simply trying to execute that:

`titleManagerAPI.giveScoreboard(playerJoinEvent.getPlayer());
titleManagerAPI.setScoreboardValueWithPlaceholders(playerJoinEvent.getPlayer(), 1, "Players remaining: %{world-online}");`

The scoreboard is shown to the player (and not the default that i set to off in config), but the placeholders aren't working:

https://gyazo.com/d5f195a38c755dbad3cb4376869083bc

I also tried with other placeholders listed in docs but no one works...

I have installed the plugin TitleManager-2.3.4.jar , no more jars. I don't need more for TItleManager placeholders, true?

Thanks you!

**Comment by precompile** [comment]
Issue still remains on paper 1.17.1
