### ISSUE TITLE
Quick question about first-join welcome title.

### ISSUE THREAD

**Issue by Rismack** [Puharesource/TitleManager#405]
Hello.

I was editing the config file of TitleManager and I saw that the welcome title has parameters like fade-in, stay, delay, etc. But the first-join title doesn't have those parameters.

Is it because those parameters are copied from the regular welcome title, or is it because you can't adjust those things at all in the first-join title?

In any case, it could be nice to be able to adjust those parameters independently. For me personally, it would be great to have the first-join title in the screen for a longer time than the welcome title. Maybe more people think like me.

Thanks!

**Comment by Puharesource** [comment]
Yes, it's copied. I don't currently have any plans to add seperate values, but I'll keep it in mind.
