### ISSUE TITLE
Bungeecord variables not working

### ISSUE THREAD

**Issue by Chompin** [Puharesource/TitleManager#41]
I currently am trying to use TItleManager on my networks hub server and the bungeecord variables are not working. I am not getting any errors and or anything.

**Comment by Chompin** [comment]
My Config:

usingConfig: true
config-version: 3
using-bungeecord: false
tabmenu:
  enabled: true
  header: '&a&o&lPsycho&5&l&oPvp'
  footer: '&c&lOnline: &e&l{BUNGEECORD-ONLINE}&c/&e&l1000'
welcome_message:
  enabled: true
  title: '&7Welcome back &a{PLAYER}&7!'
  subtitle: '&7To my server'
  fadeIn: 20
  stay: 40
  fadeOut: 20
  first-join:
    title: '&7Welcome to MyServer &a{PLAYER}'
    subtitle: '&7Hope you enjoy your stay!'
actionbar-welcome:
  enabled: true
  message: '&a&lWelcome!'
  first-join:
    message: '&2&lWelcome It''s your first time!'
number-format:
  enabled: true
  format: '#,###.##'
date-format:
  format: EEE, dd MMM yyyy HH:mm:ss z
disabled-variables:
- my-disabled-variable
- also-called-placeholders

**Comment by Puharesource** [comment]
You need to set "using-bungeecord" to true

**Comment by Puharesource** [comment]
Should be the fix to this issue.
