### ISSUE TITLE
Log4j security issue , please update your dependencies 

### ISSUE THREAD

**Issue by Tsoccerguy3** [Puharesource/TitleManager#420]
**Describe the bug**

Log4j security issue , Major Issue , Most of your dependencies are out of Date . Please update 
https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition

**To Reproduce**

**Expected behavior**

**Screenshots**

**Stacktrace / Error**
Please check the console for any errors that TitleManager might be producing.

**Server information:**
 - TitleManager version: [Example:. 2.1.5]
 - Spigot version: [Example: Spigot 1.14.4 or PaperSpigot 1.12]

**Additional context**

**Comment by Rothes** [comment]
Actually this doesn't effect plugins that only depends on **provided** Log4j2.

**Comment by Tsoccerguy3** [comment]
Yes , but I think that a dependency that you use has been removed or deleted because of the security issue . The code does not compile any more. 

G:\Dev\TitleManager>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'G:\Dev\TitleManager\build.gradle.kts' line: 5

* What went wrong:
Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.6.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.6.0')
  Searched in the following repositories:
    maven(https://dl.bintray.com/kotlin/kotlin-eap)
    MavenRepo
    maven2(https://plugins.gradle.org/m2/)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

**Comment by Tsoccerguy3** [comment]
G:\Dev\TitleManager>java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

**Comment by Tsoccerguy3** [comment]
This is what i found
https://plugins.gradle.org/m2/org/jetbrains/kotlin/jvm/org.jetbrains.kotlin.jvm.gradle.plugin/1.6.0/

org.jetbrains.kotlin.jvm.gradle.plugin-1.6.0.pom
org.jetbrains.kotlin.jvm.gradle.plugin-1.6.0.pom.md5
org.jetbrains.kotlin.jvm.gradle.plugin-1.6.0.pom.sha1

https://dl.bintray.com/kotlin/kotlin-eap

502 Bad Gateway
