### ISSUE TITLE
Scoreboard not showing

### ISSUE THREAD

**Issue by Tyloon1e** [Puharesource/TitleManager#430]
**Describe the bug**
The scoreboard isn't shown to players at all.

**To Reproduce**
Log into the server and notice it isn't showing...
You can do /tm scoreboard toggle and it will show, but after a relog it's gone again.

**Expected behavior**
I want the scoreboard to show

**Screenshots**

**Stacktrace / Error**
Please check the console for any errors that TitleManager might be producing.
No errors

**Server information:**
 - TitleManager version: 2.3.5
 - Spigot version: 1.17.1

**Additional context**

**Comment by Tyloon1e** [comment]
https://gyazo.com/e5ee219cb9088f60575698d90e01cd1b

**Comment by Tyloon1e** [comment]
Is there anything I can do about this?

**Comment by Sylensky** [comment]
I am experiencing the same issue with TM v2.3.6 on git-Purpur-1446 (MC: 1.18.1)

**Comment by Tyloon1e** [comment]
Hey I found out the issue was with another plugin... SkRayFall with something called "fast scoreboards" turned on.
FYI.

**Comment by Sylensky** [comment]
May i ask how did you determine that that plugin caused the issue?

**Comment by Tyloon1e** [comment]
I went the oldschool way and disabled all my plugins one at a time and after disabling that specific one, the scoreboard showed without issues - that specific plugin changed how scoreboards were assigned to players on join and luckily I can live without it… You might also  have a plugin installed that interferes with TitleManager’s scorebord component.

**Comment by Sylensky** [comment]
thanks. I was hoping for an easy fix but in 95% of all cases it is not. Also in this one. After doing the old way i found out it was mcmmo which i would have never expected to be culprit here. Sadly i had to disable the complete scoreboard feature of.
