### ISSUE TITLE
Trouble with updating

### ISSUE THREAD

**Issue by UntoldFury** [Puharesource/TitleManager#45]
So I'm having some problems when trying to update to the newest TitleManager version. I put the new .jar in my /plugins folder and delete the previous one, however it still alerts me that there is a new update when I log into my server. I'm not sure how to fix this, and I don't see a new option to disable the update check.

**Comment by Puharesource** [comment]
Could you please give me the output of /tm version ?

**Comment by UntoldFury** [comment]
The output reads "This server is running TitleManager v1.5.9" in green text.
I've actually realized this is happening with other plugins on my server (such as FeatherBoard) where it says they need an update, I update them, but it still give me an update notice. Do you think this is something other than TitleManager?
![tuafofq](https://cloud.githubusercontent.com/assets/11491668/8918852/84e27f50-3480-11e5-884c-9bcc9b2b52f5.png)

**Comment by Puharesource** [comment]
Yeah, seeing as you're running on version 1.5.9 and when 1.5.10, I have a feeling its an issue with your file permissions, and whenever you upload and update, you think you've uploaded it, but in reality you probably didn't have permission to edit that file or directory.

I'm just going to assume you're running on a Linux server and you've got full access to it.
To test whether or not this is the case, try to fix the permissions in that directory by using the following command (when SSH'ed to your server): `sudo chown -R the-name-of-your-user /the/path/to/your/server/plugins/folder`

This should fix your problems :)

**Comment by UntoldFury** [comment]
I'm honestly not too sure what to do with that. I'm sorry, this is the first server I've actually ran and owned on my own. I'm using a server host with Multicraft (and I'm pretty sure it runs Linux). I'm not too sure what SSH'ed means either. Sorry, I'm not too good at things like that :{

**Comment by UntoldFury** [comment]
Alright. You can go ahead and close this ticket.
I'm very sorry. It seems my stupidity got the best of me. I recently purchased a dedicated IP for my server, and they had to change my server's IP to configure everything. It seems that somewhere along the line I forgot to change my FTP host name to my new server. Thanks a lot for your help, however! I am really loving this plugin! :)
![hks8crt](https://cloud.githubusercontent.com/assets/11491668/8940546/32ee7450-3530-11e5-8263-5786f42200d3.png)

**Comment by Puharesource** [comment]
I'm glad you like it and that your problem was fixed :)
