### ISSUE TITLE
Repository is down

### ISSUE THREAD

**Issue by Rocologo** [Puharesource/TitleManager#461]
I cant access https://repo.puha.io/repo/ anymore? 

Is it down or have you moved the service?

**Comment by Puharesource** [comment]
Crap, I deleted my server, I forgot I had my repo on there. I'll get it up again soon

**Comment by Puharesource** [comment]
It should work again, please tell me if you're encountering issues.

**Comment by Rocologo** [comment]
I get some strange errors when I compile my plugin

[WARNING] Checksum validation failed, expected <!DOCTYPE but is 4c58951892f8e0c2da7b0f4c2a1184c0faae1dc2 from puha-repo for https://repo.puha.io/repo/one/lindegaard/BagOfGold/4.1.6-SNAPSHOT/maven-metadata.xml

it only happens with the repo.puha.io

**Comment by Rocologo** [comment]
Or this one

[WARNING] Checksum validation failed, expected <!DOCTYPE but is 4c58951892f8e0c2da7b0f4c2a1184c0faae1dc2 from puha-repo for https://repo.puha.io/repo/com/massivecraft/massivecore/MassiveCore/2.14.0/MassiveCore-2.14.0.jar
