### ISSUE TITLE
Multiline with animations

### ISSUE THREAD

**Issue by Ripdog1** [Puharesource/TitleManager#52]
I currently am curious to how I can have multiple lines one not an animation and one an animation for the footer

**Comment by Puharesource** [comment]
Simply add the non animated part to the animation itself

**Comment by Ripdog1** [comment]
How would you add it to the animation?
This is the footer I have currently:
  footer: '&4&m-------------------------------------------&r\nanimation:color'
This is the 'color' animation
'color':
  frames:
  - '[0;0;0]&c-&8---=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
  - '[0;0;0]&8-&c-&8--=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
  - '[0;0;0]&8--&c-&8-=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
  - '[0;0;0]&8---&c-&8=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
  - '[0;0;0]&8----=[&4&k!!!&8]&c-&8--< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
  - '[0;0;0]&8----=[&4&k!!!&8]-&c-&8-< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
  - '[0;0;0]&8----=[&4&k!!!&8]--&c-&8< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>&c-&8--=[&4&k!!!&8]=----'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>-&c-&8-=[&4&k!!!&8]=----'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>--&c-&8=[&4&k!!!&8]=----'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=&c-&8---'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=-&c-&8--'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=--&c-&8-'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=--&c-&8-'
  - '[0;0;0]&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=---&c-'

**Comment by Puharesource** [comment]
Simply add your line in-front of all of the lines in the animation like so:
````
'[0;0;0]&4&m-------------------------------------------&r\n&c-&8---=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8-&c-&8--=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8--&c-&8-=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8---&c-&8=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]&c-&8--< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]-&c-&8-< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]--&c-&8< &6{online}/{max-players} &8>---=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>&c-&8--=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>-&c-&8-=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>--&c-&8=[&4&k!!!&8]=----'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=&c-&8---'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=-&c-&8--'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=--&c-&8-'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=--&c-&8-'
'[0;0;0]&4&m-------------------------------------------&r\n&8----=[&4&k!!!&8]---< &6{online}/{max-players} &8>---=[&4&k!!!&8]=---&c-'
````

PS: You might want to add timings to those frames, since they're currently displaying for 0 ticks at a time [0;0;0] should be more like [0;2;0]

**Comment by Ripdog1** [comment]
Thank you, I really appreciate it! The timings are at 0 ticks because it displays the color going across the screen really fast to add an effect to it

**Comment by Puharesource** [comment]
Ah okay :), No problem ^^
