### ISSUE TITLE
Broadcast radius parameter

### ISSUE THREAD

**Issue by boidy** [Puharesource/TitleManager#57]
just posting as requested here:
Is it possible to broadcast a title to players in a radius? maybe add the feature /tm bc r=30 Message here ?

**Comment by Wundero** [comment]
I just wrote a quick system that could work for this, and will make a PR for it. It adds the parameter radius and works like this: /tm bc radius=30 <message> - broadcasts <message> within a radius of 30 blocks of the player. You must be a player for this to work, and if you use the world parameter, you must be in that world.

**Comment by Puharesource** [comment]
Fixed by commit 03bcec42a15824a55a4306d2e9920285fc73fb32
