### ISSUE TITLE
#36 task exception

### ISSUE THREAD

**Issue by NIK220V** [Puharesource/TitleManager#61]
Read from down to up.
1.8.7 server. Works fine on another, but not on this.
BungeeCord using is disabled.

19.09 20:56:49 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
19.09 20:56:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot187.jar:git-Spigot-f928e7a-f27339c]
19.09 20:56:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot187.jar:git-Spigot-f928e7a-f27339c]
19.09 20:56:49 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot187.jar:git-Spigot-f928e7a-f27339c]
19.09 20:56:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot187.jar:git-Spigot-f928e7a-f27339c]
19.09 20:56:49 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot187.jar:git-Spigot-f928e7a-f27339c]
19.09 20:56:49 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot187.jar:git-Spigot-f928e7a-f27339c]
19.09 20:56:49 [Server] INFO at io.puharesource.mc.titlemanager.backend.bungee.BungeeManager$1.run(BungeeManager.java:25) ~[?:?]
19.09 20:56:49 [Server] INFO java.lang.NullPointerException
19.09 20:56:49 [Server] WARN Task #36 for TitleManager v1.5.11 generated an exception

What's the way to fix this?

**Comment by Puharesource** [comment]
Could you please say what the issue was and how to fix it? in-case someone else needs help :)

**Comment by NIK220V** [comment]
I uploaded file as root and server hasn't permission to read file correctly.

**Comment by Puharesource** [comment]
Thanks :)
