### ISSUE TITLE
Animation & Text (Config)

### ISSUE THREAD

**Issue by BlazeFatality** [Puharesource/TitleManager#69]
What do you type in the config to get 2 animation in the same category?
Screenshot: http://prntscr.com/9h5llo

When I type 'animation:test1\nanimation:test2' , it came out like this
Screenshot: http://prntscr.com/9h5meu

**Comment by Puharesource** [comment]
The plugin doesn't currently support two animations in either the header or the footer. (However, it will soon).

Anyways, to fix your issue at for the time being, I suggest having a look at this reply I've given someone prior: http://i.puha.io/151213143856.png (Link in the picture: https://github.com/Puharesource/TitleManager/issues/52)

**Comment by vormison** [comment]
Какая переменна используется для TPS?

**Comment by Wundero** [comment]
Вы можете использовать PlaceholderAPI для TPS в Центрирование , но я считаю, Губка не поддерживает его еще. PlaceholderAPI : https://www.spigotmc.org/resources/placeholderapi.6245/

You can use PlaceholderAPI for TPS in Spigot, but I believe Sponge does not support it yet. PlaceholderAPI: https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by Puharesource** [comment]
Fixed by commit 03bcec42a15824a55a4306d2e9920285fc73fb32
