### ISSUE TITLE
NOTHING EDITS OR GOES HIGH PRIORITY

### ISSUE THREAD

**Issue by IronCloudSquid** [Puharesource/TitleManager#71]
It is extremely annoying that the tab won't work at all. It shows the default version of it. I edit the config and reload the plugin and server and still nothing happens. I also deleted the plugin and it still stays.

HELP

**Comment by Puharesource** [comment]
Uhmmm... Are you by any chance playing on 1.7? This plugin utilizes 1.8 features.

**Comment by IronCloudSquid** [comment]
No I am using 1.8, I have managed to remove it now but when I do have the config never works.

**Comment by Puharesource** [comment]
What are the errors that you receive in the console (I has to throw errors, if it doesn't work).

**Comment by IronCloudSquid** [comment]
I'll take a look
