### ISSUE TITLE
Hook into Worldedit/Worldguard regions.

### ISSUE THREAD

**Issue by theravensrequiem** [Puharesource/TitleManager#75]
Hey! Love what you are achieving with this plugin and keep up the great work! One request that I have though is the ability to hook into regions defined by worldedit/worldguard so I can set greetings and farewell title messages to my players when they enter and leave a specified zone, like a town or a Hub. Worldedit/worldguard has this built in so it sends a message in chat but I think using titles would be much clearer and noticeable. There is another plugin that does this, called RegionTitles, but the dev hasn't done much work on keeping it updated throughout the 1.8 cycle (and now 1.9) and hasn't communicated the status of their plans to the community in quite some time.

**Comment by Puharesource** [comment]
This sounds more like a third-party or addon plugin to me. I can't promise that I'll be making such a plugin, even though it is a good idea. I'll keep it in mind and open this issue, if I've decided to do it.
