### ISSUE TITLE
The parameters doesn't work

### ISSUE THREAD

**Issue by amatzen** [Puharesource/TitleManager#76]
The parameters in TitleManager doesn't work for me? :(

I tried to make this in Skript:
`/tm msg %player% -silent -stay 15 <nl>&aDu har lige nu &6${BALANCE}`

Thank you! :)

**Comment by Puharesource** [comment]
Do you have Vault installed? The balance placeholder requires Vault to be able to work.

**Comment by amatzen** [comment]
Yes I do have Vault installed ;) But it's any parametre I try to use :)

**Comment by amatzen** [comment]
Oh... I didn't define the problem right... I don't mean the variables/placeholders, but the parameters don't work (-silent -stay 15).

**Comment by Puharesource** [comment]
Oh yeah, I just read the question wrong :P 
Don't use a space, use an = like `-stay=15`

**Comment by amatzen** [comment]
Okay, the parameters works for me in broadcasts, but not in messages? I just replaced it with broadcast and removed the name, and it just types "-stay=15" in the message

**Comment by Puharesource** [comment]
The parameter needs to be before the player name like `/tm msg -stay=15 Puharesource Hej`

**Comment by amatzen** [comment]
Okay thank you! :)

Have a great day :D

**Comment by Puharesource** [comment]
You too ^^
