### ISSUE TITLE
'tm test' outputs that you forgot to remove this command.

### ISSUE THREAD

**Issue by mibby** [Puharesource/TitleManager#79]
`/tm test` outputs 'Sorry that I forgot about this command, please message me to remove this command from future versions of TitleManager.

**Comment by Puharesource** [comment]
Haha, thanks :P

**Comment by Puharesource** [comment]
Fixed by commit 03bcec42a15824a55a4306d2e9920285fc73fb32

**Comment by mibby** [comment]
Woo! Now to determine if v2 is better than v1.5.x. :P

**Comment by Puharesource** [comment]
It should be, the animations are smoother as well as it's got support for multiple animations on a single line.

Though there are loads of changes, that I've yet to document. Such as variables are no longer determined by `{my-variable}` they're been renamed to placeholders and now follow the pattern `%{my-placeholder}`. Animations no longer follow the pattern `animation:my-animation` they now follow the pattern `${my-animation}` and for the newly introduced scripts they follow the pattern `${script_name:My animation text}`

Also all animations now have their own file and the name is determined by the name of the file.

**Comment by mibby** [comment]
Sounds great. 

Have most of the apparent bugs been ironed out with the latest commit, such as not being able to use color codes in the action bar notice? Just something I ran across when I tried the main branch a few months ago before moving back to the stable / official 1.5.x. releases.

**Comment by Puharesource** [comment]
Yeah, it's actually a complete recode. The only things left behind from the original code is the API which has all been deprecated and replaced by a new API, that'll be easier for me to add stuff to.
