### ISSUE TITLE
Placeholders/Variables not working

### ISSUE THREAD

**Issue by Doktorwhoe** [Puharesource/TitleManager#82]
I run a 1.8 bungee server, and recently added this plugin. I noticed that the {GROUP} and {BALANCE} variables are not working... I would love for you to fix it if at all possible.
Many Thanks!

**Comment by stuntguy3000** [comment]
Do you have Vault installed?

**Comment by Puharesource** [comment]
Like @stuntguy3000 suggested, you need to install Vault for those variables to work.
