### ISSUE TITLE
adding spaces in the footer breaks it

### ISSUE THREAD

**Issue by rubota** [Puharesource/TitleManager#85]
For some reason adding any form of a space in the footer breaks the config. Yet it does perfectly fine with tons of spaces in the header. 

Working Footer: \n&3Forums:&eThisIsCrazy\n

Broken Footer \n&3Forums:&eThis IsCrazy\n

How I do add spaces without it breaking?

**Comment by Puharesource** [comment]
Remember to wrap the text with quotes, if you haven't already.
