### ISSUE TITLE
Struggling to send an animation via the API

### ISSUE THREAD

**Issue by electronicboy** [Puharesource/TitleManager#86]
Hello,

I'm trying to send tab animations via the API, was planning to do it like this so I had a bit more control over it;

http://pastebin.com/2QBivCA0

The code is basic as I'm only testing it and trying to get it to work (If that's all I was intending to do I'd be using the config file...), but have I totally missed something?

Cheers! (and thanks for the great plugin!)

**Comment by Puharesource** [comment]
What issues are you encountering?

**Comment by electronicboy** [comment]
I have no idea what to say beyond "it doesn't work";
neither calling broadcast, nor send, on the tab title animation object actually sends it to the client, Have I missed something in the API?

**Comment by Puharesource** [comment]
I don't believe so, it should work just fine o_O

Have you tried disabling the tab list functionality in the config file?

**Comment by electronicboy** [comment]
I'm just going to close this in shame, I've managed to get it working, I had the config already disabled via the config setting;
There is a chance that updating the jar (I have no idea how I didn't notice it was outdated), and I disabled the tab specifically too; I get a feeling it was probably updating the jar that solved that one; Sorry!

**Comment by Puharesource** [comment]
Haha, no problem :P
