### ISSUE TITLE
Изменение даты.

### ISSUE THREAD

**Issue by vormison** [Puharesource/TitleManager#87]
Добрый вечер.
Я живу в Российской Федерации, делаю сервер на русском языке. 
Можно ли как-нибудь изменить названия месяцев и дней недели на русский язык? (со временем всё в порядке)
Помогите, пожалуйста.

**Comment by Wundero** [comment]
Здравствуйте,
Я использую Google Translate так что простите ошибки . В конфигурации , должна быть дата - формат : Формат: раздел , и там вы можете изменить порядок дат , которые отображаются . Что касается того, что даты обеспокоены тем , я не уверен , что настраивается , как и доступ из виртуальной машины Java , так что она должна была бы быть настроены либо их , либо в системе под управлением сервера .

Надеюсь это поможет!

English:
Hello,
I am using Google translate so forgive any errors.  In the config, there should be a date-format: format: section, and there you can change the order of dates that are displayed. As far as what dates are concerned, I am not sure that is configurable as that is accessed from the Java virtual machine, so it would have to be configured either their or on the system running your server.

Hope this helps!

**Comment by Puharesource** [comment]
Я также использую Google Translate поэтому, пожалуйста, простите ошибки. Только так вы сможете изменить саму дату, изменив дату хост-машине (самого сервера).

English:
I'm also using Google Translate so please forgive any errors. The only way you'll be able to change the date itself is by changing the date of the host machine (the server itself).
