### ISSUE TITLE
1.11 compatibility

### ISSUE THREAD

**Issue by i9hdkill** [Puharesource/TitleManager#88]
Seems like plugin is not working with 1.11 clients, as the title packet changed.

**Comment by seema84** [comment]
`
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1
`

**Comment by Puharesource** [comment]
Fixed with commit: 59f85f0ac0c177159343ec145019483b40630dfa
