### ISSUE TITLE
Newline subtitle syntax does not seem to be functional in v2.0.

### ISSUE THREAD

**Issue by mibby** [Puharesource/TitleManager#93]
TitleManager 2.0.0-Pre9

The ```<nl>``` placeholder does not seem to function as intended. It doesn't split the message into a subtitle.

```
/tm bc -fadeIn=30 -stay=60 -fadeOut=30 &bServer Restart<nl>&bIn: &410 minutes
```

TitleManager 1.x, it works as intended.

**Comment by Puharesource** [comment]
<nl> has been removed in favor of \n

It was simply confusing when to use \n and when to use <nl>

**Comment by mibby** [comment]
Ah, okay. Might want to update the wiki page then. :)

**Comment by mibby** [comment]
@Puharesource The ```\n``` newline split does not seem to work for me when the command is ran from console. It might have something to do with my web panel hosting (multicraft) filtering out \n. Would it be possible to add a secondary alternative newline split syntax? :(

**Comment by Puharesource** [comment]
I'll just re-add <nl> then

**Comment by mibby** [comment]
That would be greatly appreciated. :) I looked into the console configuration and couldn't figure out where or how it is stripping special characters. Even an extra slash ```\\n``` didn't fix the issue for me. :( So an alternative syntax to use, similar to TitleManager 1.x would be wonderful.
