### ISSUE TITLE
{DISPLAYNAME} placeholder non-functional in 2.0.

### ISSUE THREAD

**Issue by mibby** [Puharesource/TitleManager#94]
The {DISPLAYNAME} placeholder variable does not function in v2.0-Pre11. 

```
  subtitle: '&bWelcome back, {DISPLAYNAME}'
```

**Comment by Puharesource** [comment]
Remember to put `%` in front of your placeholders now 😜 like `%{DISPLAYNAME}`

**Comment by mibby** [comment]
:O All these changes leaving me confused.
