### ISSUE TITLE
Reloading via '/tm reload' does not load changes made to the config in v2.0.

### ISSUE THREAD

**Issue by mibby** [Puharesource/TitleManager#95]
TitleManager v2.0-Pre11.

Making a change to the config and reloading via ```/tm reload``` does not dynamically load the changes made. You have to restart the server for the changes to take effect.

Example;

* Have a welcome-title with the subtitle of
```
  # The subtitle shown.
  subtitle: '&bWelcome back, {DISPLAYNAME}'
```
* Change {DISPLAYNAME} to 'test'
```
  # The subtitle shown.
  subtitle: '&bWelcome back, test'
```
* Reload the config in-game via ```/tm reload```
* Disconnect and reconnect to the server. The welcome title does not reflect the change made in the config. Still outputting the former set value.

Example 2;
* Start the server with 
```
  number-format:

    # Toggles this feature.
    enabled: false
```
* Change the value to true.
* Reload via ```/tm reload```
* Doesn't seem to enable.

**Comment by Puharesource** [comment]
Thanks, I'll take a look :)
