### ISSUE TITLE
How can i get ticks per second on my tab?

### ISSUE THREAD

**Issue by mauricecaaaaaben** [Puharesource/TitleManager#96]
i can't find it in placeholder api or your plugin after an hour of searching. thanks/.

**Comment by Puharesource** [comment]
TitleManager supports PlaceholderAPI, I bet it has got what you need :)
https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by mauricecaaaaaben** [comment]
i do not see it anywhere in its available tags
