### ISSUE TITLE
Balance placeholder not working

### ISSUE THREAD

**Issue by EricG66** [Puharesource/TitleManager#97]
Hi!

Everything work well in 2,0.2 except the **balance** is not working anymore.

**Comment by mauricecaaaaaben** [comment]
Are you sure you're using the placholder like this? `%{BALANCE}

**Comment by EricG66** [comment]
Yes i tried this

Eric

Le 2017-01-17 14:55, "Not My Real Name" <notifications@github.com> a écrit :

Are you sure you're using the placholder like this? `%{BALANCE}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Puharesource/TitleManager/issues/97#issuecomment-273280559>,
or mute the thread

**Comment by EricG66** [comment]
Others  users reported the same issue on your discussion forum 
https://www.spigotmc.org/threads/titlemanager.28552/page-74

**Comment by Puharesource** [comment]
Thanks for letting me, know I'm already working on a fix for this as well as other issues that have been reported.

**Comment by Puharesource** [comment]
Fixed by b1c04a6f3e149119584443a869ac2f202d0fa85f
