### ISSUE TITLE
Variables not working in Welcome Title Line

### ISSUE THREAD

**Issue by fbrower21** [Puharesource/TitleManager#98]
The variables like {PLAYER} or {DISPLAYNAME} are not working from the Welcome Title line.  Instead of it displaying the player name, it displays just {PLAYER}

**Comment by Puharesource** [comment]
The syntax for variables has changed from `{my-variable}` to now `%{my-variable}` so write `%{PLAYER}` and `%{DISPLAYNAME}` instead
