### ISSUE TITLE
Multi page scoreboard

### ISSUE THREAD

**Issue by DardBrinza** [Puharesource/TitleManager#99]
You know what it is :)
P.S. Like featherboard

**Comment by Puharesource** [comment]
How would it work? Would someone be able to run a command to show them the other page?

**Comment by Wundero** [comment]
The way featherboard does it is with "event triggers", which fire when something (e.g. killing a mob) happens on the server. This then loads a new scoreboard for a preset amount of time.

Event triggers at the moment might be a bit overkill, but using a command (for both yourself and others would be pretty handy as well) to load a new scoreboard would be useful.

**Comment by DardBrinza** [comment]
Like this:
http://pastebin.com/q6QDb6gL

**Comment by DardBrinza** [comment]
Bump :( This function in FeatherBoard is amazing, but plugin itself is terrible, no optimization and many bugs.

**Comment by MrKamenAdmin** [comment]
Will it not be implemented?
